// adjectives-db-a1.js — A1 Beginner German Adjectives (comprehensive)
const adjectivesA1 = [
  {
    "base": "groß", "level": "A1",
    "comparison": { "positive": "groß", "comparative": "größer", "superlative_predicative": "am größten", "superlative_attributive": "größte" },
    "irregular": true,
    "declension_examples": { "strong": "großer (m)", "weak": "große (f)", "mixed": "großes (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["big", "large", "tall"],
    "tip": "Comparative is irregular: groß → größer (umlaut). Used for both size and height.",
    "examples": ["Das Haus ist groß.", "Er ist ein großer Mann.", "Berlin ist größer als Hamburg."]
  },
  {
    "base": "klein", "level": "A1",
    "comparison": { "positive": "klein", "comparative": "kleiner", "superlative_predicative": "am kleinsten", "superlative_attributive": "kleinste" },
    "irregular": false,
    "declension_examples": { "strong": "kleiner (m)", "weak": "kleine (f)", "mixed": "kleines (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["small", "little", "short"],
    "tip": "Opposite of groß. Used for both size and height of people.",
    "examples": ["Die Katze ist klein.", "Er hat eine kleine Wohnung.", "Sie ist kleiner als ich."]
  },
  {
    "base": "gut", "level": "A1",
    "comparison": { "positive": "gut", "comparative": "besser", "superlative_predicative": "am besten", "superlative_attributive": "beste" },
    "irregular": true,
    "declension_examples": { "strong": "guter (m)", "weak": "gute (f)", "mixed": "gutes (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["good", "well"],
    "tip": "Highly irregular comparative and superlative: gut → besser → best-. Very common word.",
    "common_mistakes": ["Don't say 'guter' predicatively. 'Das Essen ist gut' (not 'Das Essen ist gutes')."],
    "examples": ["Das Essen ist gut.", "Er ist ein guter Freund.", "Diese Lösung ist besser.", "Das ist die beste Idee!"]
  },
  {
    "base": "schlecht", "level": "A1",
    "comparison": { "positive": "schlecht", "comparative": "schlechter", "superlative_predicative": "am schlechtesten", "superlative_attributive": "schlechteste" },
    "irregular": false,
    "declension_examples": { "strong": "schlechter (m)", "weak": "schlechte (f)", "mixed": "schlechtes (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["bad", "poor", "badly"],
    "tip": "Opposite of gut. 'Mir ist schlecht' = I feel sick/nauseous.",
    "examples": ["Das Wetter ist schlecht.", "Das ist eine schlechte Idee.", "Er fühlt sich schlecht."]
  },
  {
    "base": "neu", "level": "A1",
    "comparison": { "positive": "neu", "comparative": "neuer", "superlative_predicative": "am neuesten", "superlative_attributive": "neueste" },
    "irregular": false,
    "declension_examples": { "strong": "neuer (m)", "weak": "neue (f)", "mixed": "neues (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["new"],
    "tip": "Very common in everyday speech. 'Neu' also means 'newly/recently' as an adverb.",
    "examples": ["Er hat ein neues Auto.", "Das ist eine neue Idee.", "Was gibt es Neues?"]
  },
  {
    "base": "alt", "level": "A1",
    "comparison": { "positive": "alt", "comparative": "älter", "superlative_predicative": "am ältesten", "superlative_attributive": "älteste" },
    "irregular": true,
    "declension_examples": { "strong": "alter (m)", "weak": "alte (f)", "mixed": "altes (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["old", "aged"],
    "tip": "Comparative with umlaut: alt → älter. Used for both age and objects. To ask age: 'Wie alt bist du?'",
    "examples": ["Er ist sehr alt.", "Das ist ein altes Buch.", "Sie ist älter als ihr Bruder."]
  },
  {
    "base": "jung", "level": "A1",
    "comparison": { "positive": "jung", "comparative": "jünger", "superlative_predicative": "am jüngsten", "superlative_attributive": "jüngste" },
    "irregular": true,
    "declension_examples": { "strong": "junger (m)", "weak": "junge (f)", "mixed": "junges (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["young"],
    "tip": "Comparative with umlaut: jung → jünger. Opposite of alt.",
    "examples": ["Sie ist sehr jung.", "Das ist ein junger Mann.", "Ich bin jünger als du."]
  },
  {
    "base": "schön", "level": "A1",
    "comparison": { "positive": "schön", "comparative": "schöner", "superlative_predicative": "am schönsten", "superlative_attributive": "schönste" },
    "irregular": false,
    "declension_examples": { "strong": "schöner (m)", "weak": "schöne (f)", "mixed": "schönes (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["beautiful", "pretty", "nice", "lovely"],
    "tip": "Very versatile: beautiful (person/thing), nice (weather/day), good (time). 'Schönen Tag!' = Have a nice day!",
    "examples": ["Das Wetter ist schön.", "Sie hat schöne Augen.", "Es war ein schöner Abend."]
  },
  {
    "base": "schnell", "level": "A1",
    "comparison": { "positive": "schnell", "comparative": "schneller", "superlative_predicative": "am schnellsten", "superlative_attributive": "schnellste" },
    "irregular": false,
    "declension_examples": { "strong": "schneller (m)", "weak": "schnelle (f)", "mixed": "schnelles (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["fast", "quick", "quickly"],
    "tip": "Used both attributively and adverbially. 'Schnell!' as an exclamation = Quickly!",
    "examples": ["Das Auto fährt schnell.", "Er ist ein schneller Läufer.", "Komm schnell!"]
  },
  {
    "base": "langsam", "level": "A1",
    "comparison": { "positive": "langsam", "comparative": "langsamer", "superlative_predicative": "am langsamsten", "superlative_attributive": "langsamste" },
    "irregular": false,
    "declension_examples": { "strong": "langsamer (m)", "weak": "langsame (f)", "mixed": "langsames (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["slow", "slowly"],
    "tip": "Useful phrase: 'Sprechen Sie bitte langsamer!' = Please speak more slowly!",
    "examples": ["Das Auto fährt langsam.", "Er ist ein langsamer Arbeiter.", "Bitte sprich langsamer!"]
  },
  {
    "base": "teuer", "level": "A1",
    "comparison": { "positive": "teuer", "comparative": "teurer", "superlative_predicative": "am teuersten", "superlative_attributive": "teuerste" },
    "irregular": false,
    "declension_examples": { "strong": "teurer (m)", "weak": "teure (f)", "mixed": "teures (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["expensive", "dear"],
    "tip": "Drops -e- before endings: teuer → teure (not teuere). Opposite: günstig/billig (cheap).",
    "common_mistakes": ["'Ein teures Auto' not 'ein teueres Auto'. The -e- in the stem drops."],
    "examples": ["Das Restaurant ist teuer.", "Das ist ein teures Kleid.", "Berlin ist teurer als Leipzig."]
  },
  {
    "base": "billig", "level": "A1",
    "comparison": { "positive": "billig", "comparative": "billiger", "superlative_predicative": "am billigsten", "superlative_attributive": "billigste" },
    "irregular": false,
    "declension_examples": { "strong": "billiger (m)", "weak": "billige (f)", "mixed": "billiges (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["cheap", "inexpensive"],
    "tip": "Colloquially can imply low quality. More neutral: 'günstig' (affordable). 'Das ist billig!' can sound dismissive.",
    "examples": ["Das Buch ist billig.", "Er kauft immer die billigsten Sachen.", "Das Hotel ist billiger als das andere."]
  },
  {
    "base": "interessant", "level": "A1",
    "comparison": { "positive": "interessant", "comparative": "interessanter", "superlative_predicative": "am interessantesten", "superlative_attributive": "interessanteste" },
    "irregular": false,
    "declension_examples": { "strong": "interessanter (m)", "weak": "interessante (f)", "mixed": "interessantes (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["interesting"],
    "tip": "Superlative adds -est- because the stem ends in -t: interessant-est-en.",
    "examples": ["Das Buch ist sehr interessant.", "Er hat einen interessanten Beruf.", "Das finde ich interessant."]
  },
  {
    "base": "langweilig", "level": "A1",
    "comparison": { "positive": "langweilig", "comparative": "langweiliger", "superlative_predicative": "am langweiligsten", "superlative_attributive": "langweiligste" },
    "irregular": false,
    "declension_examples": { "strong": "langweiliger (m)", "weak": "langweilige (f)", "mixed": "langweiliges (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["boring", "dull"],
    "tip": "From 'lang' (long) + 'Weile' (while/time) — literally 'long-whiling'.",
    "examples": ["Der Film ist langweilig.", "Das Buch finde ich langweilig.", "Mir ist langweilig."]
  },
  {
    "base": "kalt", "level": "A1",
    "comparison": { "positive": "kalt", "comparative": "kälter", "superlative_predicative": "am kältesten", "superlative_attributive": "kälteste" },
    "irregular": true,
    "declension_examples": { "strong": "kalter (m)", "weak": "kalte (f)", "mixed": "kaltes (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["cold"],
    "tip": "Comparative with umlaut: kalt → kälter. 'Mir ist kalt' = I am cold.",
    "examples": ["Das Wasser ist kalt.", "Es ist ein kalter Tag.", "Mir ist kalt."]
  },
  {
    "base": "warm", "level": "A1",
    "comparison": { "positive": "warm", "comparative": "wärmer", "superlative_predicative": "am wärmsten", "superlative_attributive": "wärmste" },
    "irregular": true,
    "declension_examples": { "strong": "warmer (m)", "weak": "warme (f)", "mixed": "warmes (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["warm"],
    "tip": "Comparative with umlaut: warm → wärmer. Used for weather and objects.",
    "examples": ["Der Sommer ist warm.", "Sie trägt eine warme Jacke.", "Heute ist es wärmer."]
  },
  {
    "base": "müde", "level": "A1",
    "comparison": { "positive": "müde", "comparative": "müder", "superlative_predicative": "am müdesten", "superlative_attributive": "müdeste" },
    "irregular": false,
    "declension_examples": { "strong": "müder (m)", "weak": "müde (f)", "mixed": "müdes (n)" },
    "position": ["predicative", "attributive"],
    "translations": ["tired"],
    "tip": "Very common for expressing tiredness. 'Ich bin so müde!' Superlative adds -est- (stem ends in -d).",
    "examples": ["Ich bin sehr müde.", "Er sieht müde aus.", "Das müde Kind schläft ein."]
  },
  {
    "base": "hungrig", "level": "A1",
    "comparison": { "positive": "hungrig", "comparative": "hungriger", "superlative_predicative": "am hungrigsten", "superlative_attributive": "hungrigste" },
    "irregular": false,
    "declension_examples": { "strong": "hungriger (m)", "weak": "hungrige (f)", "mixed": "hungriges (n)" },
    "position": ["predicative", "attributive"],
    "translations": ["hungry"],
    "tip": "Also common: 'Ich habe Hunger' (I am hungry) — both forms are correct.",
    "examples": ["Ich bin hungrig.", "Die Kinder sind immer hungrig.", "Bist du noch hungrig?"]
  },
  {
    "base": "glücklich", "level": "A1",
    "comparison": { "positive": "glücklich", "comparative": "glücklicher", "superlative_predicative": "am glücklichsten", "superlative_attributive": "glücklichste" },
    "irregular": false,
    "declension_examples": { "strong": "glücklicher (m)", "weak": "glückliche (f)", "mixed": "glückliches (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["happy", "lucky"],
    "tip": "Means both 'happy' and 'lucky'. Context matters. 'Glücklicherweise' = fortunately.",
    "examples": ["Ich bin sehr glücklich.", "Sie hat ein glückliches Leben.", "Er ist das glücklichste Kind."]
  },
  {
    "base": "richtig", "level": "A1",
    "comparison": { "positive": "richtig", "comparative": "richtiger", "superlative_predicative": "am richtigsten", "superlative_attributive": "richtigste" },
    "irregular": false,
    "declension_examples": { "strong": "richtiger (m)", "weak": "richtige (f)", "mixed": "richtiges (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["correct", "right", "proper"],
    "tip": "Used colloquially to intensify: 'Das ist richtig gut!' = That's really good!",
    "examples": ["Das ist richtig.", "Ist das die richtige Antwort?", "Ich habe die richtige Entscheidung getroffen."]
  },
  {
    "base": "falsch", "level": "A1",
    "comparison": { "positive": "falsch", "comparative": "falscher", "superlative_predicative": "am falschesten", "superlative_attributive": "falscheste" },
    "irregular": false,
    "declension_examples": { "strong": "falscher (m)", "weak": "falsche (f)", "mixed": "falsches (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["wrong", "false", "incorrect"],
    "tip": "Opposite of richtig. 'Das ist falsch!' Also means 'fake': 'eine falsche Nummer' (wrong number).",
    "examples": ["Das ist falsch.", "Er hat die falsche Antwort.", "Du hast die falsche Nummer gewählt."]
  },
  {
    "base": "laut", "level": "A1",
    "comparison": { "positive": "laut", "comparative": "lauter", "superlative_predicative": "am lautesten", "superlative_attributive": "lauteste" },
    "irregular": false,
    "declension_examples": { "strong": "lauter (m)", "weak": "laute (f)", "mixed": "lautes (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["loud", "noisy"],
    "tip": "Opposite: leise (quiet). Also used as preposition: 'laut dem Bericht' (according to the report).",
    "examples": ["Die Musik ist zu laut.", "Er hat eine laute Stimme.", "Sprich nicht so laut!"]
  },
  {
    "base": "leise", "level": "A1",
    "comparison": { "positive": "leise", "comparative": "leiser", "superlative_predicative": "am leisesten", "superlative_attributive": "leiseste" },
    "irregular": false,
    "declension_examples": { "strong": "leiser (m)", "weak": "leise (f)", "mixed": "leises (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["quiet", "soft", "softly"],
    "tip": "Opposite of laut. 'Sei leise!' = Be quiet! Used for sounds and voices.",
    "examples": ["Sei bitte leise!", "Er spricht leise.", "Das ist ein leises Geräusch."]
  },
  {
    "base": "frei", "level": "A1",
    "comparison": { "positive": "frei", "comparative": "freier", "superlative_predicative": "am freisten", "superlative_attributive": "freiste" },
    "irregular": false,
    "declension_examples": { "strong": "freier (m)", "weak": "freie (f)", "mixed": "freies (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["free", "available", "vacant"],
    "tip": "Means both 'free' (liberty) and 'available/vacant'. 'Ist hier noch frei?' = Is this seat available?",
    "examples": ["Ist dieser Platz frei?", "Ich habe heute frei.", "Das ist ein freies Land."]
  },
  {
    "base": "schwer", "level": "A1",
    "comparison": { "positive": "schwer", "comparative": "schwerer", "superlative_predicative": "am schwersten", "superlative_attributive": "schwerste" },
    "irregular": false,
    "declension_examples": { "strong": "schwerer (m)", "weak": "schwere (f)", "mixed": "schweres (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["heavy", "difficult", "hard"],
    "tip": "Means both 'heavy' (weight) and 'difficult'. Context determines meaning.",
    "examples": ["Diese Tasche ist schwer.", "Deutsch ist schwer.", "Das ist eine schwere Aufgabe."]
  },
  {
    "base": "einfach", "level": "A1",
    "comparison": { "positive": "einfach", "comparative": "einfacher", "superlative_predicative": "am einfachsten", "superlative_attributive": "einfachste" },
    "irregular": false,
    "declension_examples": { "strong": "einfacher (m)", "weak": "einfache (f)", "mixed": "einfaches (n)" },
    "position": ["attributive", "predicative", "adverbial"],
    "translations": ["easy", "simple", "just"],
    "tip": "Also used as intensifier/filler: 'Das ist einfach schön!' = That's just beautiful! Also: single (ticket).",
    "examples": ["Die Übung ist einfach.", "Einmal Hamburg, einfach, bitte.", "Das ist einfach wunderbar!"]
  },
{"base":"müde","level":"A1","translations":["tired"],"examples":["Ich bin sehr müde.","Du siehst müde aus.","Warum bist du so müde?"],"comparison":{"positive":"müde","comparative":"müder","superlative_predicative":"am müdesten"}},
  {"base":"krank","level":"A1","translations":["ill","sick"],"examples":["Ich bin krank.","Sie ist krank zu Hause.","Der kranke Mann liegt im Bett."],"comparison":{"positive":"krank","comparative":"kränker","superlative_predicative":"am kränksten"},"tip":"'Ich bin krank' = I am sick. The comparative kränker is irregular."},
  {"base":"gesund","level":"A1","translations":["healthy","well"],"examples":["Ich bin gesund.","Obst ist gesund.","Bleib gesund!"],"comparison":{"positive":"gesund","comparative":"gesünder","superlative_predicative":"am gesündesten"}},
  {"base":"hungrig","level":"A1","translations":["hungry"],"examples":["Ich bin sehr hungrig.","Bist du hungrig?","Die Kinder sind hungrig."],"comparison":{"positive":"hungrig","comparative":"hungriger","superlative_predicative":"am hungrigsten"}},
  {"base":"durstig","level":"A1","translations":["thirsty"],"examples":["Ich bin durstig.","Bist du durstig?","Nach dem Sport bin ich immer durstig."],"comparison":{"positive":"durstig","comparative":"durstiger","superlative_predicative":"am durstigsten"}},
  {"base":"warm","level":"A1","translations":["warm","hot"],"examples":["Es ist heute warm.","Das Wasser ist warm.","Ich mag warmes Wetter."],"comparison":{"positive":"warm","comparative":"wärmer","superlative_predicative":"am wärmsten"}},
  {"base":"kalt","level":"A1","translations":["cold"],"examples":["Es ist kalt heute.","Das Essen ist kalt.","Im Winter ist es sehr kalt."],"comparison":{"positive":"kalt","comparative":"kälter","superlative_predicative":"am kältesten"}},
  {"base":"heiß","level":"A1","translations":["hot"],"examples":["Der Tee ist heiß.","Es ist heute sehr heiß.","Pass auf – das ist heiß!"],"comparison":{"positive":"heiß","comparative":"heißer","superlative_predicative":"am heißesten"}},
  {"base":"richtig","level":"A1","translations":["correct","right","proper"],"examples":["Das ist richtig.","Ist das richtig?","Du machst das richtig."],"comparison":{"positive":"richtig","comparative":"richtiger","superlative_predicative":"am richtigsten"}},
  {"base":"falsch","level":"A1","translations":["wrong","false","incorrect"],"examples":["Das ist falsch.","Die Antwort ist falsch.","Du liegst falsch."],"comparison":{"positive":"falsch","comparative":"falscher","superlative_predicative":"am falschesten"}},
  {"base":"leicht","level":"A1","translations":["easy","light"],"examples":["Das ist leicht.","Der Koffer ist leicht.","Die Aufgabe ist leicht."],"comparison":{"positive":"leicht","comparative":"leichter","superlative_predicative":"am leichtesten"},"tip":"leicht = both 'easy' and 'light (weight)'. Context determines meaning."},
  {"base":"schwer","level":"A1","translations":["heavy","difficult"],"examples":["Das ist schwer.","Der Koffer ist schwer.","Die Prüfung war schwer."],"comparison":{"positive":"schwer","comparative":"schwerer","superlative_predicative":"am schwersten"},"tip":"schwer = both 'heavy' and 'difficult'. Like leicht, context determines meaning."},
  {"base":"langsam","level":"A1","translations":["slow","slowly"],"examples":["Das Auto fährt langsam.","Sprich bitte langsamer!","Er ist sehr langsam."],"comparison":{"positive":"langsam","comparative":"langsamer","superlative_predicative":"am langsamsten"}},
  {"base":"schnell","level":"A1","translations":["fast","quickly"],"examples":["Das Auto ist schnell.","Geh schnell!","Er läuft sehr schnell."],"comparison":{"positive":"schnell","comparative":"schneller","superlative_predicative":"am schnellsten"}},
  {"base":"laut","level":"A1","translations":["loud","noisy"],"examples":["Die Musik ist zu laut.","Sei nicht so laut!","Er spricht laut."],"comparison":{"positive":"laut","comparative":"lauter","superlative_predicative":"am lautesten"}},
{"base":"nett","level":"A1","translations":["nice","kind","friendly"],"examples":["Du bist sehr nett.","Das ist nett von dir.","Nette Menschen mag ich."],"comparison":{"positive":"nett","comparative":"netter","superlative_predicative":"am nettesten"}},
  {"base":"lieb","level":"A1","translations":["dear","kind","sweet"],"examples":["Das ist lieb von dir.","Sei lieb!","Ein liebes Kind."],"comparison":{"positive":"lieb","comparative":"lieber","superlative_predicative":"am liebsten"},"tip":"am liebsten is also used to express strong preferences: Ich esse am liebsten Pizza."},
  {"base":"böse","level":"A1","translations":["angry","evil","bad"],"examples":["Er ist böse auf mich.","Das ist böse!","Das böse Tier."],"comparison":{"positive":"böse","comparative":"böser","superlative_predicative":"am bösesten"}},
  {"base":"traurig","level":"A1","translations":["sad"],"examples":["Ich bin traurig.","Ein trauriger Film.","Warum bist du traurig?"],"comparison":{"positive":"traurig","comparative":"trauriger","superlative_predicative":"am traurigsten"}},
  {"base":"froh","level":"A1","translations":["glad","happy"],"examples":["Ich bin froh, dass du da bist.","Froh über die Neuigkeit.","Ein frohes Fest!"],"comparison":{"positive":"froh","comparative":"froher","superlative_predicative":"am frohsten"}},
  {"base":"aufgeregt","level":"A1","translations":["excited","nervous","agitated"],"examples":["Ich bin aufgeregt.","Die Kinder sind aufgeregt.","Aufgeregt vor dem Konzert."],"comparison":{"positive":"aufgeregt","comparative":"aufgeregter","superlative_predicative":"am aufgeregtsten"}},
  {"base":"ruhig","level":"A1","translations":["quiet","calm","peaceful"],"examples":["Sei ruhig!","Das Wetter ist ruhig.","Ein ruhiges Zimmer."],"comparison":{"positive":"ruhig","comparative":"ruhiger","superlative_predicative":"am ruhigsten"}},
  {"base":"lustig","level":"A1","translations":["funny","amusing","cheerful"],"examples":["Das ist lustig!","Er ist sehr lustig.","Ein lustiger Film."],"comparison":{"positive":"lustig","comparative":"lustiger","superlative_predicative":"am lustigsten"}},
  {"base":"langweilig","level":"A1","translations":["boring","tedious"],"examples":["Der Film ist langweilig.","Das ist langweilig!","Ein langweiliger Tag."],"comparison":{"positive":"langweilig","comparative":"langweiliger","superlative_predicative":"am langweiligsten"}},
  {"base":"interessant","level":"A1","translations":["interesting"],"examples":["Das ist interessant!","Ein interessanter Mensch.","Das Buch ist sehr interessant."],"comparison":{"positive":"interessant","comparative":"interessanter","superlative_predicative":"am interessantesten"}},
  {"base":"neu","level":"A1","translations":["new","fresh"],"examples":["Das ist neu.","Ein neues Auto.","Ich habe neue Schuhe."],"comparison":{"positive":"neu","comparative":"neuer","superlative_predicative":"am neuesten"}},
  {"base":"alt","level":"A1","translations":["old"],"examples":["Das Haus ist alt.","Ein altes Buch.","Wie alt bist du?"],"comparison":{"positive":"alt","comparative":"älter","superlative_predicative":"am ältesten"}},
  {"base":"jung","level":"A1","translations":["young"],"examples":["Er ist noch jung.","Junge Leute.","Du siehst jung aus."],"comparison":{"positive":"jung","comparative":"jünger","superlative_predicative":"am jüngsten"}},
  {"base":"hoch","level":"A1","translations":["high","tall"],"examples":["Der Berg ist hoch.","Die Preise sind hoch.","Ein hohes Haus."],"comparison":{"positive":"hoch","comparative":"höher","superlative_predicative":"am höchsten"},"tip":"hoch becomes hoh- before adjective ending: ein hohes Gebäude."},
  {"base":"tief","level":"A1","translations":["deep","low"],"examples":["Das Wasser ist tief.","Ein tiefer Ton.","Die Temperaturen sind tief."],"comparison":{"positive":"tief","comparative":"tiefer","superlative_predicative":"am tiefsten"}},
  {"base":"breit","level":"A1","translations":["wide","broad"],"examples":["Die Straße ist breit.","Ein breiter Fluss.","Breit aufgestellt."],"comparison":{"positive":"breit","comparative":"breiter","superlative_predicative":"am breitesten"}},
  {"base":"eng","level":"A1","translations":["narrow","tight","close"],"examples":["Die Hose ist eng.","Eine enge Straße.","Eng befreundet."],"comparison":{"positive":"eng","comparative":"enger","superlative_predicative":"am engsten"}},
  {"base":"sauber","level":"A1","translations":["clean","neat"],"examples":["Das Zimmer ist sauber.","Saubere Hände.","Das ist sauber gemacht."],"comparison":{"positive":"sauber","comparative":"sauberer","superlative_predicative":"am saubersten"}},
  {"base":"schmutzig","level":"A1","translations":["dirty","filthy"],"examples":["Die Hände sind schmutzig.","Ein schmutziges Hemd.","Der Boden ist schmutzig."],"comparison":{"positive":"schmutzig","comparative":"schmutziger","superlative_predicative":"am schmutzigsten"}},
  {"base":"hell","level":"A1","translations":["bright","light (colour)"],"examples":["Das Zimmer ist hell.","Ein helles Blau.","Es ist hell draußen."],"comparison":{"positive":"hell","comparative":"heller","superlative_predicative":"am hellsten"}},
  {"base":"dunkel","level":"A1","translations":["dark"],"examples":["Es ist dunkel.","Ein dunkles Zimmer.","Dunkle Haare."],"comparison":{"positive":"dunkel","comparative":"dunkler","superlative_predicative":"am dunkelsten"}},
  {"base":"rund","level":"A1","translations":["round","circular"],"examples":["Der Tisch ist rund.","Eine runde Zahl.","Ein runder Geburtstag."],"comparison":{"positive":"rund","comparative":"runder","superlative_predicative":"am rundesten"}},
  {"base":"eckig","level":"A1","translations":["square","angular"],"examples":["Der Tisch ist eckig.","Eckige Formen.","Ein eckiges Gesicht."],"comparison":{"positive":"eckig","comparative":"eckiger","superlative_predicative":"am eckigsten"}},
  {"base":"süß","level":"A1","translations":["sweet","cute"],"examples":["Das ist süß!","Süße Schokolade.","Ein süßes Baby."],"comparison":{"positive":"süß","comparative":"süßer","superlative_predicative":"am süßesten"}},
  {"base":"sauer","level":"A1","translations":["sour","angry (colloquial)","fizzy"],"examples":["Die Zitrone ist sauer.","Saure Sahne.","Er ist sauer auf mich."],"comparison":{"positive":"sauer","comparative":"saurer","superlative_predicative":"am sauersten"},"tip":"sauer means sour (taste), but colloquially also angry: Er ist sauer = He is annoyed."},
{"base":"glücklich","level":"A1","translations":["happy","lucky","fortunate"],"examples":["Ich bin sehr glücklich.","Ein glückliches Kind.","Glückwunsch! (Congratulations!)"],"comparison":{"positive":"glücklich","comparative":"glücklicher","superlative_predicative":"am glücklichsten"}},
  {"base":"traurig","level":"A1","translations":["sad","sorrowful"],"examples":["Ich bin traurig.","Warum bist du so traurig?","Das ist traurig."],"comparison":{"positive":"traurig","comparative":"trauriger","superlative_predicative":"am traurigsten"}},
  {"base":"wütend","level":"A1","translations":["angry","furious","mad"],"examples":["Ich bin wütend.","Er ist sehr wütend.","Warum bist du so wütend?"],"comparison":{"positive":"wütend","comparative":"wütender","superlative_predicative":"am wütendsten"}},
  {"base":"ängstlich","level":"A1","translations":["anxious","fearful","afraid"],"examples":["Sie ist ängstlich.","Das Kind ist ängstlich.","Ich fühle mich ängstlich."],"comparison":{"positive":"ängstlich","comparative":"ängstlicher","superlative_predicative":"am ängstlichsten"}},
  {"base":"aufgeregt","level":"A1","translations":["excited","nervous","agitated"],"examples":["Ich bin aufgeregt.","Das Kind ist aufgeregt.","Warum bist du so aufgeregt?"],"comparison":{"positive":"aufgeregt","comparative":"aufgeregter","superlative_predicative":"am aufgeregtsten"}},
  {"base":"überrascht","level":"A1","translations":["surprised","astonished"],"examples":["Ich bin überrascht.","Sie sieht überrascht aus.","Das hat mich überrascht."],"comparison":{"positive":"überrascht","comparative":"überraschter","superlative_predicative":"am überraschten"}},
  {"base":"zufrieden","level":"A1","translations":["satisfied","content","happy with"],"examples":["Ich bin zufrieden.","Bist du damit zufrieden?","Er ist mit dem Ergebnis zufrieden."],"comparison":{"positive":"zufrieden","comparative":"zufriedener","superlative_predicative":"am zufriedensten"}},
  {"base":"nervös","level":"A1","translations":["nervous","anxious"],"examples":["Ich bin nervös.","Du machst mich nervös.","Vor dem Test bin ich immer nervös."],"comparison":{"positive":"nervös","comparative":"nervöser","superlative_predicative":"am nervösesten"}},
  {"base":"stolz","level":"A1","translations":["proud"],"examples":["Ich bin stolz auf dich!","Er ist sehr stolz.","Stolz auf seine Arbeit."],"comparison":{"positive":"stolz","comparative":"stolzer","superlative_predicative":"am stolzesten"},"tip":"stolz auf + Akkusativ = proud of someone/something."},
  {"base":"verliebt","level":"A1","translations":["in love","enamoured"],"examples":["Sie ist verliebt.","Er ist in sie verliebt.","Ein verliebtes Paar."],"comparison":{"positive":"verliebt","comparative":"verliebter","superlative_predicative":"am verliebten"},"tip":"verliebt in + Akkusativ = in love with."},
{"base":"klar","level":"A1","translations":["clear","obvious"],"examples":["Das ist klar.","Eine klare Antwort.","Sprich klar!","Das ist mir nicht klar."],"comparison":{"positive":"klar","comparative":"klarer","superlative_predicative":"am klarsten"}},
  {"base":"dunkel","level":"A1","translations":["dark"],"examples":["Es ist dunkel.","Das Zimmer ist dunkel.","Es wird dunkel."],"comparison":{"positive":"dunkel","comparative":"dunkler","superlative_predicative":"am dunkelsten"}},
  {"base":"hell","level":"A1","translations":["bright","light","fair"],"examples":["Das Zimmer ist hell.","Es ist noch hell.","Eine helle Farbe."],"comparison":{"positive":"hell","comparative":"heller","superlative_predicative":"am hellsten"}},
  {"base":"weich","level":"A1","translations":["soft","gentle","tender"],"examples":["Das Bett ist weich.","Die Musik ist weich.","Weiches Brot."],"comparison":{"positive":"weich","comparative":"weicher","superlative_predicative":"am weichsten"}},
  {"base":"hart","level":"A1","translations":["hard","tough","harsh"],"examples":["Das ist hart.","Ein hartes Brot.","Die Arbeit ist hart."],"comparison":{"positive":"hart","comparative":"härter","superlative_predicative":"am härtesten"}},
  {"base":"eng","level":"A1","translations":["narrow","tight","close"],"examples":["Das Hemd ist eng.","Die Straße ist eng.","Enge Freunde."],"comparison":{"positive":"eng","comparative":"enger","superlative_predicative":"am engsten"}},
  {"base":"weit","level":"A1","translations":["wide","far","distant","spacious"],"examples":["Das ist weit weg.","Ein weites Feld.","Das ist zu weit."],"comparison":{"positive":"weit","comparative":"weiter","superlative_predicative":"am weitesten"}},
  {"base":"trocken","level":"A1","translations":["dry"],"examples":["Das Handtuch ist trocken.","Das Wetter ist trocken.","Trockene Haut."],"comparison":{"positive":"trocken","comparative":"trockener","superlative_predicative":"am trockensten"}},
  {"base":"nass","level":"A1","translations":["wet","damp"],"examples":["Ich bin nass.","Das Gras ist nass.","Pass auf, das ist nass!"],"comparison":{"positive":"nass","comparative":"nasser","superlative_predicative":"am nassesten"}}
];

window.adjectivesA1 = adjectivesA1;
