window.COLLOCATIONS = [
// ──────────── COMMUNICATION ────────────
{verb:"stellen",noun:"Frage",article:"eine",example:"Darf ich eine Frage stellen?",translation:"May I ask a question?",category:"Communication",level:"A1",note:"NOT: eine Frage machen!"},
{verb:"beantworten",noun:"Frage",article:"eine/die",example:"Er hat meine Frage nicht beantwortet.",translation:"He didn't answer my question.",category:"Communication",level:"A2"},
{verb:"stellen",noun:"Antrag",article:"einen",example:"Sie hat einen Antrag gestellt.",translation:"She submitted an application.",category:"Communication",level:"B1"},
{verb:"schreiben",noun:"Nachricht",article:"eine",example:"Ich schreibe dir eine Nachricht.",translation:"I'll send you a message.",category:"Communication",level:"A1"},
{verb:"schreiben",noun:"E-Mail",article:"eine",example:"Kannst du mir eine E-Mail schreiben?",translation:"Can you send me an email?",category:"Communication",level:"A1"},
{verb:"schicken",noun:"Nachricht",article:"eine",example:"Schick mir eine Nachricht!",translation:"Send me a message!",category:"Communication",level:"A1"},
{verb:"geben",noun:"Antwort",article:"eine",example:"Ich gebe dir eine Antwort.",translation:"I'll give you an answer.",category:"Communication",level:"A2"},
{verb:"geben",noun:"Bescheid",article:"—",example:"Gib mir bitte Bescheid!",translation:"Please let me know!",category:"Communication",level:"A2"},
{verb:"halten",noun:"Vortrag",article:"einen",example:"Er hält einen Vortrag über Klimawandel.",translation:"He gives a lecture on climate change.",category:"Communication",level:"B1",note:"NOT: einen Vortrag machen"},
{verb:"führen",noun:"Gespräch",article:"ein",example:"Wir führen ein wichtiges Gespräch.",translation:"We are having an important conversation.",category:"Communication",level:"B1"},
{verb:"führen",noun:"Interview",article:"ein",example:"Die Journalistin führte ein Interview.",translation:"The journalist conducted an interview.",category:"Communication",level:"B1"},
{verb:"machen",noun:"Vorwurf",article:"einen",example:"Er macht mir Vorwürfe.",translation:"He is blaming me.",category:"Communication",level:"B2"},
{verb:"erheben",noun:"Einwand",article:"einen",example:"Sie erhebt keinen Einwand.",translation:"She raises no objection.",category:"Communication",level:"C1"},
{verb:"äußern",noun:"Meinung",article:"eine",example:"Er äußerte seine Meinung deutlich.",translation:"He expressed his opinion clearly.",category:"Communication",level:"B2"},
{verb:"übermitteln",noun:"Grüße",article:"—",example:"Bitte übermitteln Sie meine Grüße.",translation:"Please pass on my regards.",category:"Communication",level:"B2"},
{verb:"absagen",noun:"Termin",article:"einen",example:"Ich muss den Termin leider absagen.",translation:"I'm afraid I have to cancel the appointment.",category:"Communication",level:"B1"},

// ──────────── DECISIONS & ACTIONS ────────────
{verb:"treffen",noun:"Entscheidung",article:"eine",example:"Sie hat eine schwierige Entscheidung getroffen.",translation:"She made a difficult decision.",category:"Decisions",level:"B1",note:"NOT: eine Entscheidung machen"},
{verb:"treffen",noun:"Wahl",article:"eine",example:"Triff eine Wahl!",translation:"Make a choice!",category:"Decisions",level:"B1"},
{verb:"treffen",noun:"Maßnahmen",article:"—",example:"Die Regierung muss Maßnahmen treffen.",translation:"The government must take measures.",category:"Decisions",level:"B2"},
{verb:"treffen",noun:"Absprache",article:"eine",example:"Wir haben eine Absprache getroffen.",translation:"We made an arrangement.",category:"Decisions",level:"B2"},
{verb:"fällen",noun:"Urteil",article:"ein",example:"Der Richter fällte ein Urteil.",translation:"The judge passed a verdict.",category:"Decisions",level:"C1"},
{verb:"fällen",noun:"Entscheidung",article:"eine",example:"Das Komitee fällte eine Entscheidung.",translation:"The committee reached a decision.",category:"Decisions",level:"C1"},
{verb:"ziehen",noun:"Schluss",article:"einen",example:"Daraus kann man einen Schluss ziehen.",translation:"One can draw a conclusion from this.",category:"Decisions",level:"B2"},
{verb:"ziehen",noun:"Konsequenzen",article:"—",example:"Er muss die Konsequenzen ziehen.",translation:"He has to face the consequences.",category:"Decisions",level:"B2"},
{verb:"ergreifen",noun:"Initiative",article:"die",example:"Sie ergreift die Initiative.",translation:"She takes the initiative.",category:"Decisions",level:"B2"},
{verb:"ergreifen",noun:"Maßnahmen",article:"—",example:"Wir müssen Maßnahmen ergreifen.",translation:"We must take action/measures.",category:"Decisions",level:"B2"},
{verb:"leisten",noun:"Widerstand",article:"—",example:"Er leistet keinen Widerstand.",translation:"He offers no resistance.",category:"Decisions",level:"C1"},
{verb:"leisten",noun:"Verzicht",article:"—",example:"Sie leistet Verzicht auf Alkohol.",translation:"She abstains from alcohol.",category:"Decisions",level:"C1"},

// ──────────── ORGANISATION ────────────
{verb:"vereinbaren",noun:"Termin",article:"einen",example:"Können wir einen Termin vereinbaren?",translation:"Can we arrange an appointment?",category:"Organisation",level:"B1",note:"NOT: einen Termin machen (regional)"},
{verb:"machen",noun:"Termin",article:"einen",example:"Ich mache einen Termin beim Arzt.",translation:"I'm making an appointment at the doctor's.",category:"Organisation",level:"A2",note:"vereinbaren is more formal"},
{verb:"absagen",noun:"Termin",article:"einen",example:"Ich muss den Termin absagen.",translation:"I have to cancel the appointment.",category:"Organisation",level:"B1"},
{verb:"verschieben",noun:"Termin",article:"einen",example:"Können wir den Termin verschieben?",translation:"Can we postpone the appointment?",category:"Organisation",level:"B1"},
{verb:"erstellen",noun:"Liste",article:"eine",example:"Ich erstelle eine Liste der Aufgaben.",translation:"I'm creating a list of tasks.",category:"Organisation",level:"A2"},
{verb:"machen",noun:"Plan",article:"einen",example:"Lass uns einen Plan machen.",translation:"Let's make a plan.",category:"Organisation",level:"A1"},
{verb:"erstellen",noun:"Plan",article:"einen",example:"Er hat einen detaillierten Plan erstellt.",translation:"He created a detailed plan.",category:"Organisation",level:"B1"},
{verb:"halten",noun:"Ordnung",article:"—",example:"Halte bitte Ordnung!",translation:"Please keep things tidy!",category:"Organisation",level:"A2"},
{verb:"behalten",noun:"Überblick",article:"den",example:"Es ist schwer, den Überblick zu behalten.",translation:"It's hard to keep track.",category:"Organisation",level:"B2"},
{verb:"setzen",noun:"Prioritäten",article:"—",example:"Man muss Prioritäten setzen.",translation:"One must set priorities.",category:"Organisation",level:"B2"},
{verb:"aufstellen",noun:"Regeln",article:"—",example:"Die Schule stellt Regeln auf.",translation:"The school sets up rules.",category:"Organisation",level:"B1"},
{verb:"einhalten",noun:"Regeln",article:"—",example:"Alle müssen die Regeln einhalten.",translation:"Everyone must follow the rules.",category:"Organisation",level:"B1"},
{verb:"führen",noun:"Liste",article:"eine",example:"Er führt eine Liste aller Ausgaben.",translation:"He keeps a list of all expenses.",category:"Organisation",level:"B1"},
{verb:"übernehmen",noun:"Verantwortung",article:"die",example:"Sie übernimmt die Verantwortung.",translation:"She takes on the responsibility.",category:"Organisation",level:"B2"},

// ──────────── WORK & CAREER ────────────
{verb:"leisten",noun:"Arbeit",article:"gute",example:"Sie leistet gute Arbeit.",translation:"She does good work.",category:"Work",level:"B1"},
{verb:"leisten",noun:"Beitrag",article:"einen",example:"Er leistet einen wichtigen Beitrag.",translation:"He makes an important contribution.",category:"Work",level:"B2"},
{verb:"kündigen",noun:"Stelle",article:"die",example:"Er hat seine Stelle gekündigt.",translation:"He resigned from his position.",category:"Work",level:"B1"},
{verb:"bewerben",noun:"Stelle",article:"um eine",example:"Ich bewerbe mich um diese Stelle.",translation:"I'm applying for this position.",category:"Work",level:"B1"},
{verb:"antreten",noun:"Stelle",article:"eine",example:"Sie tritt ihre neue Stelle an.",translation:"She is starting her new position.",category:"Work",level:"B1"},
{verb:"erhalten",noun:"Gehaltserhöhung",article:"eine",example:"Er hat eine Gehaltserhöhung erhalten.",translation:"He received a pay rise.",category:"Work",level:"B1"},
{verb:"einreichen",noun:"Bericht",article:"einen",example:"Bitte reichen Sie den Bericht ein.",translation:"Please submit the report.",category:"Work",level:"B2"},
{verb:"abgeben",noun:"Bericht",article:"einen",example:"Ich muss morgen den Bericht abgeben.",translation:"I have to hand in the report tomorrow.",category:"Work",level:"B1"},
{verb:"machen",noun:"Überstunden",article:"—",example:"Er macht viele Überstunden.",translation:"He works a lot of overtime.",category:"Work",level:"B1"},
{verb:"einhalten",noun:"Frist",article:"eine",example:"Wir müssen die Frist einhalten.",translation:"We must meet the deadline.",category:"Work",level:"B2"},
{verb:"verpassen",noun:"Frist",article:"eine",example:"Er hat die Frist verpasst.",translation:"He missed the deadline.",category:"Work",level:"B2"},
{verb:"erzielen",noun:"Ergebnis",article:"ein",example:"Wir haben ein gutes Ergebnis erzielt.",translation:"We achieved a good result.",category:"Work",level:"B2"},
{verb:"führen",noun:"Verhandlungen",article:"—",example:"Die Firmen führen Verhandlungen.",translation:"The companies are conducting negotiations.",category:"Work",level:"C1"},
{verb:"schließen",noun:"Vertrag",article:"einen",example:"Sie haben einen Vertrag geschlossen.",translation:"They concluded a contract.",category:"Work",level:"B2"},
{verb:"übernehmen",noun:"Aufgabe",article:"eine",example:"Kannst du diese Aufgabe übernehmen?",translation:"Can you take on this task?",category:"Work",level:"B1"},
{verb:"erledigen",noun:"Aufgabe",article:"eine",example:"Ich erledige die Aufgabe bis morgen.",translation:"I'll complete the task by tomorrow.",category:"Work",level:"B1"},

// ──────────── FINANCE ────────────
{verb:"ausgeben",noun:"Geld",article:"—",example:"Er gibt viel Geld aus.",translation:"He spends a lot of money.",category:"Finance",level:"A2"},
{verb:"sparen",noun:"Geld",article:"—",example:"Wir sparen Geld für den Urlaub.",translation:"We're saving money for the holiday.",category:"Finance",level:"A2"},
{verb:"zahlen",noun:"Rechnung",article:"die",example:"Ich zahle die Rechnung.",translation:"I'll pay the bill.",category:"Finance",level:"A1"},
{verb:"begleichen",noun:"Rechnung",article:"eine",example:"Die Rechnung muss beglichen werden.",translation:"The bill must be settled.",category:"Finance",level:"B2"},
{verb:"aufnehmen",noun:"Kredit",article:"einen",example:"Sie nimmt einen Kredit auf.",translation:"She is taking out a loan.",category:"Finance",level:"B2"},
{verb:"zurückzahlen",noun:"Schulden",article:"—",example:"Er zahlt seine Schulden zurück.",translation:"He is paying back his debts.",category:"Finance",level:"B1"},
{verb:"machen",noun:"Schulden",article:"—",example:"Du solltest keine Schulden machen.",translation:"You shouldn't get into debt.",category:"Finance",level:"B1"},
{verb:"erhöhen",noun:"Preise",article:"—",example:"Die Firma erhöht die Preise.",translation:"The company is raising prices.",category:"Finance",level:"B1"},
{verb:"senken",noun:"Kosten",article:"—",example:"Wir müssen die Kosten senken.",translation:"We must reduce costs.",category:"Finance",level:"B1"},
{verb:"erzielen",noun:"Gewinn",article:"einen",example:"Das Unternehmen erzielt einen Gewinn.",translation:"The company is making a profit.",category:"Finance",level:"B2"},
{verb:"erleiden",noun:"Verlust",article:"einen",example:"Er hat einen großen Verlust erlitten.",translation:"He suffered a big loss.",category:"Finance",level:"B2"},
{verb:"eröffnen",noun:"Konto",article:"ein",example:"Ich möchte ein Konto eröffnen.",translation:"I'd like to open an account.",category:"Finance",level:"A2"},
{verb:"überweisen",noun:"Geld",article:"—",example:"Ich überweise das Geld morgen.",translation:"I'll transfer the money tomorrow.",category:"Finance",level:"B1"},
{verb:"investieren",noun:"Geld",article:"—",example:"Er investiert Geld in Aktien.",translation:"He invests money in shares.",category:"Finance",level:"B2"},

// ──────────── TRAVEL ────────────
{verb:"buchen",noun:"Flug",article:"einen",example:"Ich buche einen Flug nach Rom.",translation:"I'm booking a flight to Rome.",category:"Travel",level:"A2"},
{verb:"buchen",noun:"Hotel",article:"ein",example:"Haben Sie das Hotel gebucht?",translation:"Have you booked the hotel?",category:"Travel",level:"A2"},
{verb:"machen",noun:"Reise",article:"eine",example:"Wir machen eine Reise nach Japan.",translation:"We're taking a trip to Japan.",category:"Travel",level:"A1"},
{verb:"antreten",noun:"Reise",article:"eine",example:"Sie treten morgen die Reise an.",translation:"They set off on their journey tomorrow.",category:"Travel",level:"B1"},
{verb:"verpassen",noun:"Zug",article:"den",example:"Ich habe den Zug verpasst.",translation:"I missed the train.",category:"Travel",level:"A2"},
{verb:"nehmen",noun:"Zug",article:"den",example:"Wir nehmen den nächsten Zug.",translation:"We'll take the next train.",category:"Travel",level:"A1"},
{verb:"umsteigen",noun:"Zug",article:"—",example:"Hier müssen Sie umsteigen.",translation:"You have to change trains here.",category:"Travel",level:"A2"},
{verb:"beantragen",noun:"Visum",article:"ein",example:"Er beantragt ein Visum.",translation:"He is applying for a visa.",category:"Travel",level:"B1"},
{verb:"verlängern",noun:"Aufenthalt",article:"den",example:"Wir verlängern unseren Aufenthalt.",translation:"We're extending our stay.",category:"Travel",level:"B2"},
{verb:"unternehmen",noun:"Ausflug",article:"einen",example:"Wir unternehmen einen Ausflug.",translation:"We're going on an excursion.",category:"Travel",level:"B1"},

// ──────────── HEALTH ────────────
{verb:"machen",noun:"Untersuchung",article:"eine",example:"Der Arzt macht eine Untersuchung.",translation:"The doctor is doing an examination.",category:"Health",level:"A2"},
{verb:"verschreiben",noun:"Medikament",article:"ein",example:"Der Arzt verschreibt ein Medikament.",translation:"The doctor prescribes a medication.",category:"Health",level:"B1"},
{verb:"nehmen",noun:"Medikament",article:"ein",example:"Nehmen Sie das Medikament täglich.",translation:"Take the medication daily.",category:"Health",level:"A2"},
{verb:"erleiden",noun:"Unfall",article:"einen",example:"Er hat einen Unfall erlitten.",translation:"He suffered an accident.",category:"Health",level:"B1"},
{verb:"haben",noun:"Schmerzen",article:"—",example:"Ich habe starke Schmerzen.",translation:"I have severe pain.",category:"Health",level:"A2"},
{verb:"klagen über",noun:"Schmerzen",article:"—",example:"Er klagt über Rückenschmerzen.",translation:"He complains of back pain.",category:"Health",level:"B1"},
{verb:"sich erholen",noun:"Krankheit",article:"von einer",example:"Sie erholt sich von einer schweren Krankheit.",translation:"She is recovering from a serious illness.",category:"Health",level:"B1"},
{verb:"einliefern",noun:"Krankenhaus",article:"ins",example:"Er wurde ins Krankenhaus eingeliefert.",translation:"He was admitted to hospital.",category:"Health",level:"B1"},
{verb:"entlassen",noun:"Krankenhaus",article:"aus dem",example:"Sie wurde aus dem Krankenhaus entlassen.",translation:"She was discharged from hospital.",category:"Health",level:"B2"},
{verb:"achten auf",noun:"Gesundheit",article:"die",example:"Man sollte auf seine Gesundheit achten.",translation:"One should take care of one's health.",category:"Health",level:"B1"},
{verb:"verbessern",noun:"Gesundheit",article:"die",example:"Ich möchte meine Gesundheit verbessern.",translation:"I want to improve my health.",category:"Health",level:"A2"},
{verb:"pflegen",noun:"Patient",article:"einen",example:"Die Krankenschwester pflegt den Patienten.",translation:"The nurse cares for the patient.",category:"Health",level:"B2"},

// ──────────── EDUCATION ────────────
{verb:"machen",noun:"Prüfung",article:"eine",example:"Ich mache morgen eine Prüfung.",translation:"I have an exam tomorrow.",category:"Education",level:"A2"},
{verb:"bestehen",noun:"Prüfung",article:"eine",example:"Sie hat die Prüfung bestanden.",translation:"She passed the exam.",category:"Education",level:"A2"},
{verb:"nicht bestehen",noun:"Prüfung",article:"eine",example:"Er hat die Prüfung nicht bestanden.",translation:"He failed the exam.",category:"Education",level:"A2"},
{verb:"ablegen",noun:"Prüfung",article:"eine",example:"Die Schüler legen ihre Abschlussprüfung ab.",translation:"The students sit their final exam.",category:"Education",level:"B2"},
{verb:"lernen",noun:"Vokabeln",article:"—",example:"Ich lerne täglich neue Vokabeln.",translation:"I learn new vocabulary every day.",category:"Education",level:"A1"},
{verb:"machen",noun:"Hausaufgaben",article:"—",example:"Hast du deine Hausaufgaben gemacht?",translation:"Have you done your homework?",category:"Education",level:"A1"},
{verb:"besuchen",noun:"Kurs",article:"einen",example:"Ich besuche einen Deutschkurs.",translation:"I'm attending a German course.",category:"Education",level:"A2"},
{verb:"absolvieren",noun:"Studium",article:"ein",example:"Er absolviert ein Studium in Medizin.",translation:"He is completing a degree in medicine.",category:"Education",level:"B2"},
{verb:"erwerben",noun:"Kenntnisse",article:"—",example:"Sie erwirbt neue Kenntnisse.",translation:"She is acquiring new knowledge.",category:"Education",level:"B2"},
{verb:"schreiben",noun:"Aufsatz",article:"einen",example:"Die Schüler schreiben einen Aufsatz.",translation:"The pupils write an essay.",category:"Education",level:"B1"},

// ──────────── RELATIONSHIPS ────────────
{verb:"kennenlernen",noun:"Person",article:"eine",example:"Ich habe eine interessante Person kennengelernt.",translation:"I met an interesting person.",category:"Relationships",level:"A2"},
{verb:"schließen",noun:"Freundschaft",article:"eine",example:"Sie haben schnell eine Freundschaft geschlossen.",translation:"They quickly formed a friendship.",category:"Relationships",level:"B1"},
{verb:"beenden",noun:"Beziehung",article:"eine",example:"Er hat die Beziehung beendet.",translation:"He ended the relationship.",category:"Relationships",level:"B1"},
{verb:"eingehen",noun:"Beziehung",article:"eine",example:"Sie geht eine neue Beziehung ein.",translation:"She is entering into a new relationship.",category:"Relationships",level:"B2"},
{verb:"halten",noun:"Kontakt",article:"—",example:"Wir halten Kontakt über soziale Medien.",translation:"We keep in touch via social media.",category:"Relationships",level:"B1"},
{verb:"verlieren",noun:"Kontakt",article:"den",example:"Wir haben den Kontakt verloren.",translation:"We lost contact.",category:"Relationships",level:"B1"},
{verb:"machen",noun:"Kompliment",article:"ein",example:"Er machte ihr ein Kompliment.",translation:"He gave her a compliment.",category:"Relationships",level:"B1"},
{verb:"geben",noun:"Rat",article:"einen",example:"Kannst du mir einen Rat geben?",translation:"Can you give me some advice?",category:"Relationships",level:"A2"},
{verb:"nehmen",noun:"Rücksicht",article:"—",example:"Du musst Rücksicht nehmen.",translation:"You must show consideration.",category:"Relationships",level:"B2"},
{verb:"zeigen",noun:"Verständnis",article:"—",example:"Er zeigt kein Verständnis.",translation:"He shows no understanding.",category:"Relationships",level:"B2"},
{verb:"heiraten",noun:"—",article:"—",example:"Sie haben letztes Jahr geheiratet.",translation:"They got married last year.",category:"Relationships",level:"A2"},
{verb:"sich trennen",noun:"—",article:"—",example:"Sie haben sich getrennt.",translation:"They separated.",category:"Relationships",level:"B1"},
{verb:"streiten",noun:"—",article:"—",example:"Sie streiten sich oft.",translation:"They argue a lot.",category:"Relationships",level:"A2"},
{verb:"versöhnen",noun:"—",article:"—",example:"Sie haben sich wieder versöhnt.",translation:"They made up again.",category:"Relationships",level:"B2"},

// ──────────── TIME ────────────
{verb:"verbringen",noun:"Zeit",article:"—",example:"Wir verbringen viel Zeit zusammen.",translation:"We spend a lot of time together.",category:"Time",level:"A2"},
{verb:"verschwenden",noun:"Zeit",article:"—",example:"Verschwende keine Zeit!",translation:"Don't waste time!",category:"Time",level:"B1"},
{verb:"sparen",noun:"Zeit",article:"—",example:"Diese App spart viel Zeit.",translation:"This app saves a lot of time.",category:"Time",level:"A2"},
{verb:"nehmen",noun:"Zeit",article:"sich die",example:"Nimm dir die Zeit, es richtig zu machen.",translation:"Take the time to do it properly.",category:"Time",level:"B1"},
{verb:"haben",noun:"Zeit",article:"keine",example:"Ich habe keine Zeit dafür.",translation:"I don't have time for that.",category:"Time",level:"A1"},
{verb:"einplanen",noun:"Zeit",article:"—",example:"Ich habe Zeit dafür eingeplant.",translation:"I have planned time for it.",category:"Time",level:"B1"},
{verb:"einhalten",noun:"Termin",article:"einen",example:"Wir müssen den Termin einhalten.",translation:"We must keep the appointment.",category:"Time",level:"B1"},

// ──────────── EMOTIONS & MENTAL STATE ────────────
{verb:"bekommen",noun:"Angst",article:"—",example:"Er bekommt Angst vor dem Zahnarzt.",translation:"He becomes afraid of the dentist.",category:"Emotions",level:"A2"},
{verb:"haben",noun:"Angst",article:"—",example:"Ich habe Angst vor Spinnen.",translation:"I'm afraid of spiders.",category:"Emotions",level:"A1"},
{verb:"machen",noun:"Mut",article:"—",example:"Mach dir Mut!",translation:"Cheer up! / Give yourself courage!",category:"Emotions",level:"B1"},
{verb:"verlieren",noun:"Geduld",article:"die",example:"Er verliert schnell die Geduld.",translation:"He quickly loses patience.",category:"Emotions",level:"B1"},
{verb:"verlieren",noun:"Mut",article:"den",example:"Verlier nicht den Mut!",translation:"Don't lose courage!",category:"Emotions",level:"B1"},
{verb:"haben",noun:"Freude",article:"—",example:"Es macht mir Freude.",translation:"It gives me joy.",category:"Emotions",level:"A2"},
{verb:"empfinden",noun:"Schmerz",article:"—",example:"Sie empfindet großen Schmerz.",translation:"She feels great pain.",category:"Emotions",level:"C1"},
{verb:"bewahren",noun:"Ruhe",article:"die",example:"Bewahr die Ruhe!",translation:"Keep calm!",category:"Emotions",level:"B1"},
{verb:"verlieren",noun:"Fassung",article:"die",example:"Er verlor die Fassung.",translation:"He lost his composure.",category:"Emotions",level:"B2"},
{verb:"zeigen",noun:"Gefühle",article:"—",example:"Er zeigt selten seine Gefühle.",translation:"He rarely shows his feelings.",category:"Emotions",level:"B1"},

// ──────────── ARGUMENTS & OPINIONS ────────────
{verb:"vertreten",noun:"Meinung",article:"eine",example:"Er vertritt eine klare Meinung.",translation:"He holds a clear opinion.",category:"Arguments",level:"B2"},
{verb:"teilen",noun:"Meinung",article:"eine",example:"Ich teile deine Meinung nicht.",translation:"I don't share your opinion.",category:"Arguments",level:"B1"},
{verb:"ändern",noun:"Meinung",article:"die",example:"Sie hat ihre Meinung geändert.",translation:"She changed her mind.",category:"Arguments",level:"B1"},
{verb:"erheben",noun:"Vorwurf",article:"einen",example:"Er erhebt schwere Vorwürfe.",translation:"He makes serious accusations.",category:"Arguments",level:"C1"},
{verb:"widersprechen",noun:"—",article:"—",example:"Ich muss dir widersprechen.",translation:"I have to contradict you.",category:"Arguments",level:"B2"},
{verb:"bestehen auf",noun:"—",article:"—",example:"Sie besteht auf ihrer Forderung.",translation:"She insists on her demand.",category:"Arguments",level:"B2"},
{verb:"anerkennen",noun:"Fehler",article:"einen",example:"Er erkennt seinen Fehler an.",translation:"He acknowledges his mistake.",category:"Arguments",level:"B2"},
{verb:"zugeben",noun:"Fehler",article:"einen",example:"Sie gibt ihren Fehler zu.",translation:"She admits her mistake.",category:"Arguments",level:"B1"},
{verb:"eingestehen",noun:"Fehler",article:"einen",example:"Es fällt ihm schwer, seinen Fehler einzugestehen.",translation:"It's hard for him to admit his mistake.",category:"Arguments",level:"C1"},

// ──────────── ENVIRONMENT & NATURE ────────────
{verb:"schützen",noun:"Umwelt",article:"die",example:"Wir müssen die Umwelt schützen.",translation:"We must protect the environment.",category:"Environment",level:"B1"},
{verb:"schaden",noun:"Umwelt",article:"der",example:"Plastik schadet der Umwelt.",translation:"Plastic harms the environment.",category:"Environment",level:"B1"},
{verb:"reduzieren",noun:"Emissionen",article:"die",example:"Wir müssen die Emissionen reduzieren.",translation:"We must reduce emissions.",category:"Environment",level:"B2"},
{verb:"verursachen",noun:"Schäden",article:"—",example:"Das Hochwasser verursacht große Schäden.",translation:"The flood causes major damage.",category:"Environment",level:"B2"},
{verb:"retten",noun:"Klima",article:"das",example:"Wir müssen das Klima retten.",translation:"We must save the climate.",category:"Environment",level:"B1"},
{verb:"nutzen",noun:"Energie",article:"erneuerbare",example:"Sie nutzen erneuerbare Energie.",translation:"They use renewable energy.",category:"Environment",level:"B2"},
{verb:"vermeiden",noun:"Müll",article:"—",example:"Versuche, Müll zu vermeiden.",translation:"Try to avoid waste.",category:"Environment",level:"B1"},
{verb:"trennen",noun:"Müll",article:"den",example:"In Deutschland muss man den Müll trennen.",translation:"In Germany you have to separate the rubbish.",category:"Environment",level:"A2"},

// ──────────── LEGAL ────────────
{verb:"erstatten",noun:"Anzeige",article:"eine",example:"Sie erstattet Anzeige gegen ihn.",translation:"She reports him to the police.",category:"Legal",level:"B2"},
{verb:"klagen",noun:"—",article:"—",example:"Er klagt gegen das Unternehmen.",translation:"He is suing the company.",category:"Legal",level:"B2"},
{verb:"schließen",noun:"Einigung",article:"eine",example:"Sie schlossen eine Einigung.",translation:"They reached a settlement.",category:"Legal",level:"B2"},
{verb:"unterzeichnen",noun:"Vertrag",article:"einen",example:"Beide Seiten unterzeichnen den Vertrag.",translation:"Both sides sign the contract.",category:"Legal",level:"B2"},
{verb:"verstoßen gegen",noun:"Gesetz",article:"ein",example:"Er verstößt gegen das Gesetz.",translation:"He is breaking the law.",category:"Legal",level:"B2"},
{verb:"einhalten",noun:"Gesetz",article:"ein",example:"Alle müssen das Gesetz einhalten.",translation:"Everyone must obey the law.",category:"Legal",level:"B2"},
{verb:"verhängen",noun:"Strafe",article:"eine",example:"Das Gericht verhängt eine Strafe.",translation:"The court imposes a penalty.",category:"Legal",level:"C1"},
{verb:"beantragen",noun:"Asyl",article:"—",example:"Er beantragt Asyl.",translation:"He applies for asylum.",category:"Legal",level:"B2"},

// ──────────── SOCIETY ────────────
{verb:"leisten",noun:"Dienst",article:"einen",example:"Er leistet seinen Militärdienst.",translation:"He does his military service.",category:"Society",level:"B2"},
{verb:"übernehmen",noun:"Rolle",article:"eine",example:"Frauen übernehmen wichtige Rollen.",translation:"Women take on important roles.",category:"Society",level:"B2"},
{verb:"spielen",noun:"Rolle",article:"eine",example:"Geld spielt eine große Rolle.",translation:"Money plays a big role.",category:"Society",level:"B1"},
{verb:"leisten",noun:"Ehrenamt",article:"ein",example:"Er leistet ein Ehrenamt.",translation:"He does voluntary work.",category:"Society",level:"B2"},
{verb:"stärken",noun:"Demokratie",article:"die",example:"Wir müssen die Demokratie stärken.",translation:"We must strengthen democracy.",category:"Society",level:"B2"},
{verb:"fördern",noun:"Integration",article:"die",example:"Das Programm fördert die Integration.",translation:"The programme promotes integration.",category:"Society",level:"B2"},

// ──────────── TRICKY PAIRS ────────────
{verb:"stellen",noun:"Frage",article:"eine",example:"eine Frage stellen (NOT: machen)",translation:"to ask a question",category:"Tricky Pairs",level:"A1",note:"❌ eine Frage machen ✅ eine Frage stellen"},
{verb:"treffen",noun:"Entscheidung",article:"eine",example:"eine Entscheidung treffen (NOT: machen)",translation:"to make a decision",category:"Tricky Pairs",level:"B1",note:"❌ eine Entscheidung machen ✅ eine Entscheidung treffen"},
{verb:"halten",noun:"Vortrag",article:"einen",example:"einen Vortrag halten (NOT: machen)",translation:"to give a lecture",category:"Tricky Pairs",level:"B1",note:"❌ einen Vortrag machen ✅ einen Vortrag halten"},
{verb:"vereinbaren",noun:"Termin",article:"einen",example:"einen Termin vereinbaren (NOT: machen — colloquial ok)",translation:"to arrange an appointment",category:"Tricky Pairs",level:"B1",note:"✅ vereinbaren (formal) = arrange. machen = informal/regional"},
{verb:"begehen",noun:"Fehler",article:"einen",example:"Wir haben einen Fehler begangen.",translation:"We committed a mistake.",category:"Tricky Pairs",level:"B2",note:"begehen is more formal; machen (make a mistake) is common too"},
{verb:"schließen",noun:"Vertrag",article:"einen",example:"einen Vertrag schließen (NOT: machen)",translation:"to conclude/sign a contract",category:"Tricky Pairs",level:"B2",note:"❌ einen Vertrag machen ✅ einen Vertrag schließen / unterzeichnen"},
{verb:"erheben",noun:"Vorwurf",article:"einen",example:"einen Vorwurf erheben (NOT: machen — though both used)",translation:"to make an accusation/reproach",category:"Tricky Pairs",level:"C1",note:"erheben = more formal. machen (Vorwürfe machen) is common"},
{verb:"erstatten",noun:"Bericht",article:"—",example:"Bitte erstatten Sie Bericht.",translation:"Please report / give a report.",category:"Tricky Pairs",level:"C1",note:"❌ einen Bericht machen ✅ Bericht erstatten (formal)"},
{verb:"Rechenschaft ablegen",noun:"—",article:"—",example:"Er muss Rechenschaft ablegen.",translation:"He must give an account / be accountable.",category:"Tricky Pairs",level:"C1",note:"Fixed phrase — always 'Rechenschaft ablegen'"},
{verb:"leisten",noun:"Beitrag",article:"einen",example:"Sie leistet einen wertvollen Beitrag.",translation:"She makes a valuable contribution.",category:"Tricky Pairs",level:"B2",note:"❌ einen Beitrag machen ✅ einen Beitrag leisten"},
];
