// sentences.js — 5000 Common German Daily Sentences
// window.CONVERSATIONS = [ ... ]
// Each: { id, title, category, level, exchanges: [{de, en}] }

window.CONVERSATIONS = [

// ═══════════════════════════════════════════════════════
//  GREETINGS & FIRST CONTACT
// ═══════════════════════════════════════════════════════
{id:"greet-1",title:"First Meeting",category:"Greetings",level:"A1",exchanges:[
  {de:"Guten Morgen!",en:"Good morning!"},
  {de:"Guten Morgen! Wie geht es Ihnen?",en:"Good morning! How are you?"},
  {de:"Danke, gut. Und Ihnen?",en:"Thanks, fine. And you?"},
  {de:"Auch gut, danke. Ich bin Thomas.",en:"Also fine, thanks. I'm Thomas."},
  {de:"Freut mich! Ich bin Maria.",en:"Nice to meet you! I'm Maria."},
  {de:"Woher kommen Sie?",en:"Where are you from?"},
  {de:"Ich komme aus Spanien. Und Sie?",en:"I'm from Spain. And you?"},
  {de:"Ich bin aus München. Leben Sie schon lange hier?",en:"I'm from Munich. Have you been living here long?"},
  {de:"Erst seit drei Monaten. Die Stadt ist wunderschön.",en:"Only for three months. The city is beautiful."},
  {de:"Ja, das stimmt. Willkommen in Deutschland!",en:"Yes, that's true. Welcome to Germany!"},
]},
{id:"greet-2",title:"Casual Greeting Between Friends",category:"Greetings",level:"A1",exchanges:[
  {de:"Hey, wie geht's?",en:"Hey, how's it going?"},
  {de:"Gut, und dir?",en:"Good, and you?"},
  {de:"Super, danke! Was machst du so?",en:"Great, thanks! What are you up to?"},
  {de:"Nicht viel. Ich war gerade einkaufen.",en:"Not much. I was just shopping."},
  {de:"Cool. Hast du heute Abend Zeit?",en:"Cool. Do you have time this evening?"},
  {de:"Ja, warum? Was ist los?",en:"Yes, why? What's going on?"},
  {de:"Wir gehen in die neue Bar in der Altstadt.",en:"We're going to the new bar in the old town."},
  {de:"Oh, das klingt gut! Um wie viel Uhr?",en:"Oh, that sounds good! What time?"},
  {de:"Um acht. Wir treffen uns vor der Bar.",en:"At eight. We'll meet in front of the bar."},
  {de:"Perfekt. Bis heute Abend!",en:"Perfect. See you tonight!"},
]},
{id:"greet-3",title:"Saying Goodbye",category:"Greetings",level:"A1",exchanges:[
  {de:"Ich muss jetzt leider gehen.",en:"I'm afraid I have to go now."},
  {de:"Schon? Schade!",en:"Already? What a pity!"},
  {de:"Ja, ich habe noch einen Termin.",en:"Yes, I still have an appointment."},
  {de:"Kein Problem. Wann sehen wir uns wieder?",en:"No problem. When will we see each other again?"},
  {de:"Vielleicht am Wochenende?",en:"Maybe at the weekend?"},
  {de:"Gerne! Ich schreibe dir eine Nachricht.",en:"Sure! I'll send you a message."},
  {de:"Perfekt. Tschüss und schönen Tag noch!",en:"Perfect. Bye and have a nice day!"},
  {de:"Dir auch! Bis bald!",en:"You too! See you soon!"},
]},
{id:"greet-4",title:"Formal Introduction",category:"Greetings",level:"A2",exchanges:[
  {de:"Guten Tag. Darf ich mich vorstellen?",en:"Good day. May I introduce myself?"},
  {de:"Natürlich, bitte.",en:"Of course, please."},
  {de:"Mein Name ist Lena Braun. Ich arbeite bei der Firma Schmidt.",en:"My name is Lena Braun. I work at the Schmidt company."},
  {de:"Freut mich, Frau Braun. Ich bin Klaus Weber, Abteilungsleiter.",en:"Pleased to meet you, Ms Braun. I'm Klaus Weber, department head."},
  {de:"Ich bin neu hier und lerne noch alle kennen.",en:"I'm new here and still getting to know everyone."},
  {de:"Wenn Sie Fragen haben, stehe ich gerne zur Verfügung.",en:"If you have questions, I'm happy to help."},
  {de:"Vielen Dank. Das ist sehr nett von Ihnen.",en:"Many thanks. That's very kind of you."},
  {de:"Gern geschehen. Willkommen im Team!",en:"You're welcome. Welcome to the team!"},
]},
{id:"greet-5",title:"Greeting a Neighbour",category:"Greetings",level:"A1",exchanges:[
  {de:"Hallo Frau Müller! Wie geht es Ihnen?",en:"Hello Mrs Müller! How are you?"},
  {de:"Danke, es geht. Und Ihnen?",en:"Thanks, all right. And you?"},
  {de:"Gut, danke. Das Wetter ist heute schön, oder?",en:"Good, thanks. The weather is nice today, isn't it?"},
  {de:"Ja, endlich! Es hat so lange geregnet.",en:"Yes, finally! It has rained for so long."},
  {de:"Ich hoffe, es bleibt so schön.",en:"I hope it stays this nice."},
  {de:"Das hoffe ich auch. Einen schönen Tag!",en:"I hope so too. Have a nice day!"},
  {de:"Danke, Ihnen auch!",en:"Thanks, you too!"},
]},

// ═══════════════════════════════════════════════════════
//  SMALL TALK
// ═══════════════════════════════════════════════════════
{id:"small-1",title:"Talking About the Weekend",category:"Small Talk",level:"A2",exchanges:[
  {de:"Was hast du am Wochenende gemacht?",en:"What did you do at the weekend?"},
  {de:"Ich war bei meinen Eltern. Und du?",en:"I was at my parents'. And you?"},
  {de:"Ich bin ins Kino gegangen. Ein toller Film!",en:"I went to the cinema. A great film!"},
  {de:"Was war das für ein Film?",en:"What film was it?"},
  {de:"Ein neuer Thriller. Sehr spannend!",en:"A new thriller. Very exciting!"},
  {de:"Das klingt interessant. Wie heißt er?",en:"That sounds interesting. What's it called?"},
  {de:"'Dunkelheit'. Ich kann ihn nur empfehlen.",en:"'Darkness'. I can only recommend it."},
  {de:"Ich schaue ihn mir vielleicht auch an.",en:"Maybe I'll watch it too."},
  {de:"Unbedingt! Du wirst ihn lieben.",en:"Definitely! You'll love it."},
]},
{id:"small-2",title:"Talking About the Weather",category:"Small Talk",level:"A1",exchanges:[
  {de:"Heute ist es aber kalt, oder?",en:"It's really cold today, isn't it?"},
  {de:"Ja, typisch für November.",en:"Yes, typical for November."},
  {de:"Ich mag den Winter nicht besonders.",en:"I don't particularly like winter."},
  {de:"Wirklich? Ich finde ihn schön. Besonders mit Schnee.",en:"Really? I think it's nice. Especially with snow."},
  {de:"Schnee ist zwar schön, aber ich friere zu schnell.",en:"Snow is nice, but I get cold too quickly."},
  {de:"Hast du einen dicken Mantel?",en:"Do you have a thick coat?"},
  {de:"Ja, aber er reicht nicht! (lacht)",en:"Yes, but it's not enough! (laughs)"},
  {de:"Dann brauchst du Handschuhe und eine Mütze dazu.",en:"Then you need gloves and a hat too."},
]},
{id:"small-3",title:"Weekend Plans",category:"Small Talk",level:"A2",exchanges:[
  {de:"Was machst du dieses Wochenende?",en:"What are you doing this weekend?"},
  {de:"Ich gehe vielleicht wandern. Wenn das Wetter gut ist.",en:"I might go hiking. If the weather is good."},
  {de:"Oh schön! Wohin willst du?",en:"Oh lovely! Where do you want to go?"},
  {de:"Ich dachte an den Schwarzwald.",en:"I was thinking of the Black Forest."},
  {de:"Das ist eine tolle Idee. Fährst du alleine?",en:"That's a great idea. Are you going alone?"},
  {de:"Nein, mit ein paar Freunden. Wir sind zu fünft.",en:"No, with a few friends. There are five of us."},
  {de:"Das klingt toll. Ich bin ein bisschen neidisch!",en:"That sounds great. I'm a little envious!"},
  {de:"Du kannst nächstes Mal mitkommen, wenn du möchtest.",en:"You can come along next time if you like."},
  {de:"Wirklich? Das wäre super!",en:"Really? That would be great!"},
]},
{id:"small-4",title:"Talking About Hobbies",category:"Small Talk",level:"A2",exchanges:[
  {de:"Was machst du in deiner Freizeit?",en:"What do you do in your free time?"},
  {de:"Ich lese viel und koche gerne.",en:"I read a lot and enjoy cooking."},
  {de:"Kochen? Was kochst du am liebsten?",en:"Cooking? What do you like cooking most?"},
  {de:"Ich koche oft italienisch. Pasta, Risotto...",en:"I often cook Italian food. Pasta, risotto..."},
  {de:"Oh, ich liebe Pasta! Hast du ein Lieblingsrezept?",en:"Oh, I love pasta! Do you have a favourite recipe?"},
  {de:"Ja! Spaghetti Carbonara. Ganz einfach aber lecker.",en:"Yes! Spaghetti carbonara. Very simple but delicious."},
  {de:"Das muss ich unbedingt ausprobieren.",en:"I must definitely try that."},
  {de:"Komm doch mal vorbei! Ich koche für dich.",en:"Come over sometime! I'll cook for you."},
  {de:"Das ist sehr nett! Ich komme gerne.",en:"That's very kind! I'd love to come."},
]},
{id:"small-5",title:"Talking About Family",category:"Small Talk",level:"A2",exchanges:[
  {de:"Hast du Geschwister?",en:"Do you have siblings?"},
  {de:"Ja, ich habe einen Bruder und eine Schwester.",en:"Yes, I have a brother and a sister."},
  {de:"Wohnen sie noch bei deinen Eltern?",en:"Do they still live with your parents?"},
  {de:"Mein Bruder schon, aber meine Schwester wohnt in Hamburg.",en:"My brother does, but my sister lives in Hamburg."},
  {de:"Siehst du deine Familie oft?",en:"Do you see your family often?"},
  {de:"Ungefähr einmal im Monat. Wir sind nicht so nah beieinander.",en:"About once a month. We're not that close to each other."},
  {de:"Das ist schade. Ich vermisse meine Familie auch.",en:"That's a shame. I miss my family too."},
  {de:"Woher kommst du ursprünglich?",en:"Where are you originally from?"},
  {de:"Aus der Türkei. Ich bin vor fünf Jahren hierhergezogen.",en:"From Turkey. I moved here five years ago."},
  {de:"Das ist spannend. Gefällt es dir hier?",en:"That's interesting. Do you like it here?"},
  {de:"Ja, sehr gut. Ich fühle mich hier zu Hause.",en:"Yes, very much. I feel at home here."},
]},

// ═══════════════════════════════════════════════════════
//  DAILY ROUTINES
// ═══════════════════════════════════════════════════════
{id:"daily-1",title:"Morning Routine",category:"Daily Life",level:"A1",exchanges:[
  {de:"Wann stehst du normalerweise auf?",en:"When do you normally get up?"},
  {de:"Um halb sieben. Und du?",en:"At half past six. And you?"},
  {de:"Ich stehe um sechs auf. Ich bin ein Frühaufsteher.",en:"I get up at six. I'm an early riser."},
  {de:"Das ist früh! Was machst du dann zuerst?",en:"That's early! What do you do first then?"},
  {de:"Ich mache zuerst Sport. Dann dusche ich und frühstücke.",en:"First I exercise. Then I shower and have breakfast."},
  {de:"Was isst du zum Frühstück?",en:"What do you have for breakfast?"},
  {de:"Meistens Müsli mit Joghurt oder Toast.",en:"Usually muesli with yoghurt or toast."},
  {de:"Klingst gut. Ich trinke nur Kaffee und bin dann los.",en:"Sounds good. I just drink coffee and then I'm off."},
  {de:"Ohne Frühstück? Das wäre nichts für mich!",en:"Without breakfast? That wouldn't do for me!"},
]},
{id:"daily-2",title:"Evening Routine",category:"Daily Life",level:"A2",exchanges:[
  {de:"Was machst du nach der Arbeit?",en:"What do you do after work?"},
  {de:"Meistens koche ich und schaue dann etwas fern.",en:"Usually I cook and then watch something on TV."},
  {de:"Was schaust du gerne?",en:"What do you like watching?"},
  {de:"Serien, hauptsächlich. Gerade schaue ich eine deutsche Serie.",en:"Series, mainly. I'm currently watching a German series."},
  {de:"Welche denn?",en:"Which one?"},
  {de:"'Dark'. Sehr komplex, aber fesselnd.",en:"'Dark'. Very complex, but gripping."},
  {de:"Die kenne ich! Wirklich genial.",en:"I know it! Really brilliant."},
  {de:"Ja! Ich schlafe danach aber schlecht (lacht).",en:"Yes! But I sleep badly afterwards (laughs)."},
  {de:"Zu viele Rätsel im Kopf!",en:"Too many puzzles in your head!"},
]},
{id:"daily-3",title:"Cooking at Home",category:"Daily Life",level:"A2",exchanges:[
  {de:"Kochst du oft zu Hause?",en:"Do you often cook at home?"},
  {de:"Ja, fast jeden Tag. Ich esse lieber zu Hause.",en:"Yes, almost every day. I prefer eating at home."},
  {de:"Das ist auch gesünder und günstiger, oder?",en:"That's also healthier and cheaper, isn't it?"},
  {de:"Stimmt. Und ich kann selbst entscheiden, was ich esse.",en:"True. And I can decide myself what I eat."},
  {de:"Was kochst du heute Abend?",en:"What are you cooking this evening?"},
  {de:"Ich weiß noch nicht. Vielleicht Suppe oder ein Omelett.",en:"I don't know yet. Maybe soup or an omelette."},
  {de:"Hast du alle Zutaten?",en:"Do you have all the ingredients?"},
  {de:"Ich glaube schon. Wenn nicht, gehe ich noch kurz einkaufen.",en:"I think so. If not, I'll quickly go shopping."},
]},
{id:"daily-4",title:"Household Chores",category:"Daily Life",level:"A2",exchanges:[
  {de:"Wer putzt bei euch die Wohnung?",en:"Who cleans the flat for you?"},
  {de:"Wir teilen uns die Hausarbeit.",en:"We share the household chores."},
  {de:"Das ist fair. Was machst du am liebsten?",en:"That's fair. What do you like doing most?"},
  {de:"Ehrlich gesagt? Am liebsten gar nichts. (lacht)",en:"Honestly? I'd rather nothing at all. (laughs)"},
  {de:"Haha! Aber was musst du am meisten machen?",en:"Haha! But what do you have to do most?"},
  {de:"Ich wasche meistens ab und sauge Staub.",en:"I usually wash up and vacuum."},
  {de:"Und dein Mitbewohner?",en:"And your flatmate?"},
  {de:"Er kocht und putzt das Badezimmer. Funktioniert ganz gut.",en:"He cooks and cleans the bathroom. Works quite well."},
]},
{id:"daily-5",title:"Shopping for Groceries",category:"Daily Life",level:"A1",exchanges:[
  {de:"Ich muss noch einkaufen gehen.",en:"I still need to go shopping."},
  {de:"Was brauchst du?",en:"What do you need?"},
  {de:"Brot, Milch, Eier und etwas Gemüse.",en:"Bread, milk, eggs and some vegetables."},
  {de:"Gehst du zum Supermarkt oder zum Markt?",en:"Are you going to the supermarket or the market?"},
  {de:"Zum Supermarkt. Der Markt hat jetzt zu.",en:"To the supermarket. The market is closed now."},
  {de:"Welchen nimmst du?",en:"Which one are you going to?"},
  {de:"Den REWE um die Ecke. Der ist nah.",en:"The REWE around the corner. It's nearby."},
  {de:"Kannst du mir etwas mitbringen? Ich brauche Käse.",en:"Can you bring me something? I need cheese."},
  {de:"Klar, welchen Käse?",en:"Sure, which cheese?"},
  {de:"Emmentaler, wenn möglich.",en:"Emmental if possible."},
]},
{id:"daily-6",title:"Going to Bed",category:"Daily Life",level:"A1",exchanges:[
  {de:"Ich bin total müde. Ich gehe gleich schlafen.",en:"I'm totally tired. I'm going to sleep soon."},
  {de:"Wann stehst du morgen auf?",en:"When are you getting up tomorrow?"},
  {de:"Um sieben. Ich habe einen frühen Termin.",en:"At seven. I have an early appointment."},
  {de:"Das ist aber früh. Gute Nacht dann!",en:"That is early. Good night then!"},
  {de:"Gute Nacht! Schlaf gut.",en:"Good night! Sleep well."},
  {de:"Danke, dir auch.",en:"Thanks, you too."},
]},

// ═══════════════════════════════════════════════════════
//  AT THE RESTAURANT
// ═══════════════════════════════════════════════════════
{id:"rest-1",title:"Getting a Table",category:"Restaurant",level:"A1",exchanges:[
  {de:"Guten Abend! Haben Sie einen Tisch für zwei Personen?",en:"Good evening! Do you have a table for two?"},
  {de:"Ja, haben Sie reserviert?",en:"Yes, have you reserved?"},
  {de:"Nein, leider nicht.",en:"No, unfortunately not."},
  {de:"Kein Problem. Bitte folgen Sie mir.",en:"No problem. Please follow me."},
  {de:"Danke. Können wir lieber am Fenster sitzen?",en:"Thank you. Could we sit by the window preferably?"},
  {de:"Natürlich, gerne. Hier ist Ihre Speisekarte.",en:"Of course, with pleasure. Here is your menu."},
  {de:"Danke sehr. Können wir auch die Weinkarte haben?",en:"Thank you very much. Can we also have the wine list?"},
  {de:"Selbstverständlich. Ich bringe sie sofort.",en:"Of course. I'll bring it right away."},
]},
{id:"rest-2",title:"Ordering Food",category:"Restaurant",level:"A1",exchanges:[
  {de:"Was darf ich Ihnen bringen?",en:"What can I bring you?"},
  {de:"Ich hätte gerne die Tagessuppe als Vorspeise.",en:"I'd like the soup of the day as a starter."},
  {de:"Und als Hauptgericht?",en:"And as a main course?"},
  {de:"Das Schnitzel mit Pommes, bitte.",en:"The schnitzel with chips, please."},
  {de:"Und für Sie?",en:"And for you?"},
  {de:"Ich nehme den Salat und dann das Lachsfilet.",en:"I'll have the salad and then the salmon fillet."},
  {de:"Möchten Sie etwas trinken?",en:"Would you like something to drink?"},
  {de:"Ein Mineralwasser und ein Glas Weißwein, bitte.",en:"A sparkling water and a glass of white wine, please."},
  {de:"Sehr gerne. Kommt sofort.",en:"With pleasure. Coming right up."},
]},
{id:"rest-3",title:"Paying the Bill",category:"Restaurant",level:"A1",exchanges:[
  {de:"Entschuldigung, die Rechnung bitte.",en:"Excuse me, the bill please."},
  {de:"Ja, natürlich. Zusammen oder getrennt?",en:"Yes, of course. Together or separately?"},
  {de:"Getrennt bitte.",en:"Separately please."},
  {de:"Kein Problem. Das macht 18,50 Euro.",en:"No problem. That's 18.50 euros."},
  {de:"Hier sind 20 Euro. Stimmt so.",en:"Here's 20 euros. Keep the change."},
  {de:"Vielen Dank! Hat es Ihnen geschmeckt?",en:"Thank you very much! Did you enjoy your meal?"},
  {de:"Ja, es war ausgezeichnet. Vielen Dank.",en:"Yes, it was excellent. Thank you very much."},
  {de:"Das freut uns sehr. Auf Wiedersehen!",en:"We're very pleased to hear that. Goodbye!"},
]},
{id:"rest-4",title:"Complaint at the Restaurant",category:"Restaurant",level:"B1",exchanges:[
  {de:"Entschuldigung, ich glaube, da ist ein Fehler in meiner Bestellung.",en:"Excuse me, I think there's a mistake in my order."},
  {de:"Oh, das tut mir leid. Was ist das Problem?",en:"Oh, I'm sorry. What's the problem?"},
  {de:"Ich hatte das Schnitzel bestellt, aber das hier ist Fisch.",en:"I had ordered the schnitzel, but this is fish."},
  {de:"Oh, es tut mir sehr leid! Das war ein Missverständnis.",en:"Oh, I'm very sorry! That was a misunderstanding."},
  {de:"Kein Problem. Können Sie mir bitte das Schnitzel bringen?",en:"No problem. Could you please bring me the schnitzel?"},
  {de:"Natürlich, sofort. Und für die Unannehmlichkeit bekommen Sie ein Dessert aufs Haus.",en:"Of course, right away. And for the inconvenience you'll get a dessert on the house."},
  {de:"Oh, das ist sehr nett. Danke!",en:"Oh, that's very kind. Thank you!"},
]},
{id:"rest-5",title:"Asking About the Menu",category:"Restaurant",level:"A2",exchanges:[
  {de:"Ich kann mich noch nicht entscheiden. Was empfehlen Sie?",en:"I can't decide yet. What do you recommend?"},
  {de:"Das Rinderfilet ist heute sehr gut.",en:"The beef fillet is very good today."},
  {de:"Ist es sehr teuer?",en:"Is it very expensive?"},
  {de:"Es kostet 24 Euro. Das ist unser bestes Gericht.",en:"It costs 24 euros. It's our best dish."},
  {de:"Ich bin Vegetarier. Was gibt es ohne Fleisch?",en:"I'm vegetarian. What is there without meat?"},
  {de:"Wir haben eine sehr gute Gemüsepfanne und Pasta.",en:"We have a very good vegetable pan and pasta."},
  {de:"Die Gemüsepfanne klingt gut. Ist sie scharf?",en:"The vegetable pan sounds good. Is it spicy?"},
  {de:"Nein, aber wir können Chili dazugeben, wenn Sie möchten.",en:"No, but we can add chilli if you like."},
  {de:"Nein danke, ohne Chili bitte.",en:"No thank you, without chilli please."},
]},

// ═══════════════════════════════════════════════════════
//  SHOPPING
// ═══════════════════════════════════════════════════════
{id:"shop-1",title:"In a Clothing Shop",category:"Shopping",level:"A2",exchanges:[
  {de:"Kann ich Ihnen helfen?",en:"Can I help you?"},
  {de:"Ja, ich suche ein Hemd für eine Hochzeit.",en:"Yes, I'm looking for a shirt for a wedding."},
  {de:"Welche Größe haben Sie?",en:"What size are you?"},
  {de:"Ich glaube Größe M.",en:"I think size M."},
  {de:"Welche Farbe darf es sein?",en:"What colour would you like?"},
  {de:"Weiß oder Hellblau wäre schön.",en:"White or light blue would be nice."},
  {de:"Hier hätten wir einige Modelle. Das hier zum Beispiel.",en:"We have some models here. This one for example."},
  {de:"Das gefällt mir sehr. Kann ich es anprobieren?",en:"I like it very much. Can I try it on?"},
  {de:"Natürlich. Die Umkleidekabinen sind da hinten.",en:"Of course. The changing rooms are at the back there."},
]},
{id:"shop-2",title:"Buying Electronics",category:"Shopping",level:"B1",exchanges:[
  {de:"Ich interessiere mich für einen neuen Laptop.",en:"I'm interested in a new laptop."},
  {de:"Für welchen Zweck brauchen Sie ihn?",en:"What do you need it for?"},
  {de:"Hauptsächlich für die Arbeit und manchmal zum Surfen.",en:"Mainly for work and sometimes for browsing."},
  {de:"Welches Budget haben Sie?",en:"What's your budget?"},
  {de:"Ungefähr 800 bis 1000 Euro.",en:"About 800 to 1000 euros."},
  {de:"In diesem Bereich hätte ich drei gute Modelle.",en:"In this range I have three good models."},
  {de:"Was ist der Unterschied zwischen diesen beiden?",en:"What's the difference between these two?"},
  {de:"Dieser hier hat mehr Arbeitsspeicher, der andere einen besseren Akku.",en:"This one has more RAM, the other has a better battery."},
  {de:"Ich nehme den mit dem besseren Akku. Ich reise viel.",en:"I'll take the one with the better battery. I travel a lot."},
  {de:"Gute Wahl. Soll ich ihn einpacken?",en:"Good choice. Shall I wrap it up?"},
]},
{id:"shop-3",title:"Returning an Item",category:"Shopping",level:"B1",exchanges:[
  {de:"Guten Tag. Ich möchte dieses Produkt umtauschen.",en:"Good day. I'd like to exchange this product."},
  {de:"Was ist das Problem damit?",en:"What's the problem with it?"},
  {de:"Es hat einen Defekt. Schauen Sie, hier ist ein Riss.",en:"It has a defect. Look, there's a crack here."},
  {de:"Oh, das tut mir leid. Haben Sie den Kassenbon?",en:"Oh, I'm sorry. Do you have the receipt?"},
  {de:"Ja, hier bitte.",en:"Yes, here you go."},
  {de:"Wann haben Sie es gekauft?",en:"When did you buy it?"},
  {de:"Vor drei Tagen.",en:"Three days ago."},
  {de:"Kein Problem. Möchten Sie es umtauschen oder lieber zurückgeben?",en:"No problem. Would you like to exchange it or return it?"},
  {de:"Ich würde es gerne umtauschen, wenn möglich.",en:"I'd like to exchange it if possible."},
  {de:"Selbstverständlich. Bitte folgen Sie mir.",en:"Of course. Please follow me."},
]},
{id:"shop-4",title:"At the Market",category:"Shopping",level:"A2",exchanges:[
  {de:"Guten Morgen! Was darf es sein?",en:"Good morning! What can I get you?"},
  {de:"Ich hätte gerne ein Kilo Tomaten.",en:"I'd like a kilo of tomatoes."},
  {de:"Hier sind frische Tomaten vom heutigen Morgen.",en:"Here are fresh tomatoes from this morning."},
  {de:"Sehr schön! Und haben Sie auch Erdbeeren?",en:"Very nice! And do you have strawberries too?"},
  {de:"Ja, hier. Die sind heute sehr süß.",en:"Yes, here. They're very sweet today."},
  {de:"Prima. Dann nehme ich noch zwei Schalen.",en:"Great. Then I'll take two punnets as well."},
  {de:"Sonst noch etwas?",en:"Anything else?"},
  {de:"Nein danke. Was macht das zusammen?",en:"No thank you. What does that come to altogether?"},
  {de:"Das macht vier Euro zwanzig.",en:"That's four euros twenty."},
  {de:"Hier bitte, und stimmt so.",en:"Here you go, and keep the change."},
]},

// ═══════════════════════════════════════════════════════
//  TRANSPORT & DIRECTIONS
// ═══════════════════════════════════════════════════════
{id:"trans-1",title:"At the Train Station",category:"Transport",level:"A2",exchanges:[
  {de:"Entschuldigung, wann fährt der nächste Zug nach Frankfurt?",en:"Excuse me, when does the next train to Frankfurt leave?"},
  {de:"Um 14:35 Uhr, von Gleis 7.",en:"At 14:35, from platform 7."},
  {de:"Muss ich umsteigen?",en:"Do I have to change?"},
  {de:"Ja, in Mannheim. Sie haben dort 12 Minuten Aufenthalt.",en:"Yes, in Mannheim. You have 12 minutes there."},
  {de:"Und wie lange dauert die Fahrt insgesamt?",en:"And how long does the journey take in total?"},
  {de:"Ungefähr zwei Stunden und zwanzig Minuten.",en:"About two hours and twenty minutes."},
  {de:"Danke. Wo kann ich eine Fahrkarte kaufen?",en:"Thank you. Where can I buy a ticket?"},
  {de:"Am Schalter da drüben oder am Automaten.",en:"At the counter over there or at the machine."},
]},
{id:"trans-2",title:"Asking for Directions",category:"Transport",level:"A2",exchanges:[
  {de:"Entschuldigung, wie komme ich zum Bahnhof?",en:"Excuse me, how do I get to the station?"},
  {de:"Gehen Sie hier geradeaus bis zur Ampel.",en:"Go straight ahead here to the traffic lights."},
  {de:"Und dann?",en:"And then?"},
  {de:"Dann biegen Sie links ab und gehen noch etwa 200 Meter.",en:"Then turn left and walk about another 200 metres."},
  {de:"Ist es weit?",en:"Is it far?"},
  {de:"Nein, nur etwa fünf Minuten zu Fuß.",en:"No, only about five minutes on foot."},
  {de:"Super, vielen Dank!",en:"Great, many thanks!"},
  {de:"Gern geschehen. Gute Reise!",en:"You're welcome. Have a good journey!"},
]},
{id:"trans-3",title:"Taking a Bus",category:"Transport",level:"A1",exchanges:[
  {de:"Entschuldigung, fährt dieser Bus zum Rathaus?",en:"Excuse me, does this bus go to the town hall?"},
  {de:"Nein, Sie müssen die Linie 4 nehmen.",en:"No, you need to take line 4."},
  {de:"Wo hält die?",en:"Where does it stop?"},
  {de:"An der nächsten Haltestelle, dort vorne.",en:"At the next stop, there in front."},
  {de:"Wie oft fährt sie?",en:"How often does it run?"},
  {de:"Alle zehn Minuten.",en:"Every ten minutes."},
  {de:"Danke! Und wie viele Stationen sind es?",en:"Thank you! And how many stops is it?"},
  {de:"Nur drei. Sie können die Haltestellen auf der Anzeige lesen.",en:"Only three. You can read the stops on the display."},
]},
{id:"trans-4",title:"In a Taxi",category:"Transport",level:"A1",exchanges:[
  {de:"Zum Flughafen, bitte.",en:"To the airport, please."},
  {de:"Welches Terminal?",en:"Which terminal?"},
  {de:"Terminal 1, bitte.",en:"Terminal 1, please."},
  {de:"In Ordnung. Haben Sie Gepäck?",en:"All right. Do you have luggage?"},
  {de:"Ja, einen Koffer im Kofferraum.",en:"Yes, a suitcase in the boot."},
  {de:"Gut. Wann muss Ihr Flug abgehen?",en:"Good. When does your flight leave?"},
  {de:"Um 16 Uhr. Schaffen wir das?",en:"At 4 pm. Will we make it?"},
  {de:"Bei diesem Verkehr? Ich denke schon. Es dauert etwa 30 Minuten.",en:"In this traffic? I think so. It takes about 30 minutes."},
  {de:"Was kostet die Fahrt ungefähr?",en:"About how much does the journey cost?"},
  {de:"Ungefähr 35 Euro, je nach Verkehr.",en:"About 35 euros, depending on traffic."},
]},
{id:"trans-5",title:"Renting a Car",category:"Transport",level:"B1",exchanges:[
  {de:"Guten Tag. Ich möchte ein Auto für drei Tage mieten.",en:"Good day. I'd like to rent a car for three days."},
  {de:"Welche Fahrzeugklasse wünschen Sie?",en:"What vehicle class would you like?"},
  {de:"Eine Mittelklasse wäre gut. Nicht zu groß, nicht zu klein.",en:"A mid-range would be good. Not too big, not too small."},
  {de:"Haben Sie einen Führerschein dabei?",en:"Do you have a driving licence with you?"},
  {de:"Ja, hier ist er.",en:"Yes, here it is."},
  {de:"Wie weit planen Sie zu fahren?",en:"How far are you planning to drive?"},
  {de:"Ungefähr 500 Kilometer insgesamt.",en:"About 500 kilometres in total."},
  {de:"Dann empfehle ich das All-inclusive-Paket. Versicherung inklusive.",en:"Then I recommend the all-inclusive package. Insurance included."},
  {de:"Klingt gut. Was kostet das?",en:"Sounds good. What does that cost?"},
  {de:"89 Euro pro Tag. Gesamt also 267 Euro.",en:"89 euros per day. So 267 euros in total."},
]},

// ═══════════════════════════════════════════════════════
//  HEALTH & DOCTOR'S
// ═══════════════════════════════════════════════════════
{id:"health-1",title:"Making a Doctor's Appointment",category:"Health",level:"A2",exchanges:[
  {de:"Praxis Dr. Wagner, guten Tag!",en:"Dr Wagner's practice, good day!"},
  {de:"Guten Tag. Ich brauche einen Termin.",en:"Good day. I need an appointment."},
  {de:"Was haben Sie für Beschwerden?",en:"What are your symptoms?"},
  {de:"Ich habe seit drei Tagen starke Halsschmerzen.",en:"I've had a severe sore throat for three days."},
  {de:"Wann sind Sie frei?",en:"When are you free?"},
  {de:"Am besten morgen Vormittag.",en:"Tomorrow morning would be best."},
  {de:"Wie wäre Ihnen morgen um zehn Uhr?",en:"How would ten o'clock tomorrow suit you?"},
  {de:"Das passt sehr gut. Wie ist die Adresse?",en:"That suits me very well. What's the address?"},
  {de:"Bergstraße 14. Wir freuen uns auf Sie.",en:"Bergstrasse 14. We look forward to seeing you."},
]},
{id:"health-2",title:"At the Doctor's",category:"Health",level:"B1",exchanges:[
  {de:"Was kann ich für Sie tun?",en:"What can I do for you?"},
  {de:"Ich habe seit einer Woche Kopfschmerzen und Schwindel.",en:"I've had headaches and dizziness for a week."},
  {de:"Haben Sie Fieber?",en:"Do you have a fever?"},
  {de:"Ich hatte gestern 38 Grad.",en:"I had 38 degrees yesterday."},
  {de:"Haben Sie andere Symptome? Husten, Schnupfen?",en:"Do you have other symptoms? Cough, runny nose?"},
  {de:"Ja, leichten Husten.",en:"Yes, a slight cough."},
  {de:"Ich höre Sie ab. Atmen Sie tief ein bitte.",en:"I'll listen to your chest. Please breathe in deeply."},
  {de:"Das sieht nach einem grippalen Infekt aus.",en:"This looks like a flu-like infection."},
  {de:"Was soll ich dagegen tun?",en:"What should I do about it?"},
  {de:"Ich verschreibe Ihnen Tabletten. Und viel Ruhe und Flüssigkeit.",en:"I'll prescribe you tablets. And plenty of rest and fluids."},
  {de:"Wie lange bin ich krankgeschrieben?",en:"How long am I signed off sick?"},
  {de:"Ich schreibe Sie für drei Tage krank.",en:"I'll sign you off for three days."},
]},
{id:"health-3",title:"At the Pharmacy",category:"Health",level:"A2",exchanges:[
  {de:"Guten Tag. Ich brauche etwas gegen Kopfschmerzen.",en:"Good day. I need something for headaches."},
  {de:"Haben Sie ein Rezept?",en:"Do you have a prescription?"},
  {de:"Nein. Haben Sie etwas Rezeptfreies?",en:"No. Do you have something without a prescription?"},
  {de:"Ja, natürlich. Hier haben wir Ibuprofen oder Paracetamol.",en:"Yes, of course. We have ibuprofen or paracetamol here."},
  {de:"Was empfehlen Sie?",en:"What do you recommend?"},
  {de:"Ibuprofen wirkt auch gegen Entzündungen. Sehr beliebt.",en:"Ibuprofen also works against inflammation. Very popular."},
  {de:"Gut, dann nehme ich das. Wie oft darf ich es nehmen?",en:"Good, then I'll take that. How often may I take it?"},
  {de:"Maximal dreimal täglich mit Abstand von 6 bis 8 Stunden.",en:"Maximum three times a day with 6 to 8 hours in between."},
  {de:"Danke sehr. Was kostet es?",en:"Thank you very much. How much does it cost?"},
  {de:"4,50 Euro, bitte.",en:"4.50 euros, please."},
]},
{id:"health-4",title:"Emergency",category:"Health",level:"B1",exchanges:[
  {de:"Hilfe! Mein Freund ist hingefallen und kann nicht aufstehen!",en:"Help! My friend has fallen and can't get up!"},
  {de:"Ich rufe sofort den Notruf! 112.",en:"I'll call emergency services immediately! 112."},
  {de:"Notruf 112, was ist Ihr Notfall?",en:"Emergency services 112, what is your emergency?"},
  {de:"Mein Freund ist gestürzt und klagt über starke Schmerzen im Bein.",en:"My friend has fallen and is complaining of severe pain in his leg."},
  {de:"Wo befinden Sie sich genau?",en:"Where exactly are you?"},
  {de:"Wir sind im Stadtpark, nahe dem Springbrunnen.",en:"We're in the city park, near the fountain."},
  {de:"Ist er bei Bewusstsein?",en:"Is he conscious?"},
  {de:"Ja, er spricht, aber er hat sehr starke Schmerzen.",en:"Yes, he's talking, but he's in very severe pain."},
  {de:"Gut. Bewegen Sie ihn nicht. Der Krankenwagen kommt in fünf Minuten.",en:"Good. Don't move him. The ambulance will be there in five minutes."},
]},

// ═══════════════════════════════════════════════════════
//  WORK & OFFICE
// ═══════════════════════════════════════════════════════
{id:"work-1",title:"Job Interview",category:"Work",level:"B1",exchanges:[
  {de:"Guten Morgen, Herr Müller. Nehmen Sie bitte Platz.",en:"Good morning, Mr Müller. Please have a seat."},
  {de:"Guten Morgen. Danke, das ist sehr nett.",en:"Good morning. Thank you, that's very kind."},
  {de:"Erzählen Sie uns kurz über sich und Ihren beruflichen Hintergrund.",en:"Tell us briefly about yourself and your professional background."},
  {de:"Ich habe Betriebswirtschaft studiert und arbeite seit fünf Jahren im Marketing.",en:"I studied business administration and have been working in marketing for five years."},
  {de:"Warum möchten Sie zu uns wechseln?",en:"Why do you want to move to us?"},
  {de:"Ich suche neue Herausforderungen und Ihr Unternehmen hat einen sehr guten Ruf.",en:"I'm looking for new challenges and your company has a very good reputation."},
  {de:"Was sind Ihre Stärken?",en:"What are your strengths?"},
  {de:"Ich bin sehr kommunikativ und arbeite gut im Team.",en:"I'm very communicative and work well in a team."},
  {de:"Haben Sie noch Fragen an uns?",en:"Do you have any questions for us?"},
  {de:"Ja. Wie sieht das Onboarding für neue Mitarbeiter aus?",en:"Yes. What does the onboarding look like for new employees?"},
  {de:"Wir haben ein strukturiertes Programm von vier Wochen.",en:"We have a structured four-week programme."},
]},
{id:"work-2",title:"Meeting at Work",category:"Work",level:"B1",exchanges:[
  {de:"Guten Morgen alle. Fangen wir pünktlich an.",en:"Good morning everyone. Let's start on time."},
  {de:"Kurz zur Tagesordnung: wir besprechen das neue Projekt.",en:"Briefly to the agenda: we're discussing the new project."},
  {de:"Wo stehen wir aktuell?",en:"Where do we currently stand?"},
  {de:"Wir liegen etwas hinter dem Zeitplan.",en:"We're slightly behind schedule."},
  {de:"Was sind die Gründe dafür?",en:"What are the reasons for that?"},
  {de:"Wir hatten technische Probleme in der letzten Woche.",en:"We had technical problems last week."},
  {de:"Wie können wir den Rückstand aufholen?",en:"How can we catch up on the backlog?"},
  {de:"Wir könnten das Team vorübergehend verstärken.",en:"We could temporarily reinforce the team."},
  {de:"Gute Idee. Wer kann noch Kapazitäten frei machen?",en:"Good idea. Who can free up more capacity?"},
  {de:"Ich könnte drei Stunden pro Woche übernehmen.",en:"I could take on three hours a week."},
]},
{id:"work-3",title:"Calling in Sick",category:"Work",level:"B1",exchanges:[
  {de:"Guten Morgen, hier ist Anna Braun.",en:"Good morning, this is Anna Braun."},
  {de:"Guten Morgen, Frau Braun. Was kann ich für Sie tun?",en:"Good morning, Ms Braun. What can I do for you?"},
  {de:"Ich wollte mich krankengelden. Ich fühle mich heute nicht gut.",en:"I wanted to call in sick. I don't feel well today."},
  {de:"Oh, das tut mir leid. Was fehlt Ihnen?",en:"Oh, I'm sorry to hear that. What's wrong with you?"},
  {de:"Ich habe Fieber und starke Halsschmerzen.",en:"I have a fever and a severe sore throat."},
  {de:"Haben Sie einen Arzttermin?",en:"Do you have a doctor's appointment?"},
  {de:"Ja, ich gehe heute Nachmittag zum Arzt.",en:"Yes, I'm going to the doctor this afternoon."},
  {de:"Gut. Wann können wir mit Ihrer Rückkehr rechnen?",en:"Good. When can we expect you back?"},
  {de:"Ich hoffe, spätestens in zwei Tagen.",en:"I hope in two days at the latest."},
  {de:"Gut, dann gute Besserung!",en:"All right, then get well soon!"},
]},
{id:"work-4",title:"Talking About a Project",category:"Work",level:"B2",exchanges:[
  {de:"Wie läuft das neue Projekt?",en:"How is the new project going?"},
  {de:"Gut, aber wir haben noch einige Herausforderungen.",en:"Well, but we still have some challenges."},
  {de:"Was genau?",en:"What exactly?"},
  {de:"Das Budget ist etwas knapp, und wir brauchen mehr Zeit für die Tests.",en:"The budget is a bit tight, and we need more time for testing."},
  {de:"Haben Sie das mit dem Management besprochen?",en:"Have you discussed this with management?"},
  {de:"Noch nicht. Wir wollen erst eine Lösung ausarbeiten.",en:"Not yet. We want to work out a solution first."},
  {de:"Das ist sinnvoll. Brauchen Sie Unterstützung dabei?",en:"That makes sense. Do you need support with that?"},
  {de:"Ja, etwas mehr Ressourcen wären hilfreich.",en:"Yes, a few more resources would be helpful."},
  {de:"Ich schaue, was ich arrangieren kann.",en:"I'll see what I can arrange."},
]},
{id:"work-5",title:"Working from Home",category:"Work",level:"B1",exchanges:[
  {de:"Arbeitest du heute von zu Hause?",en:"Are you working from home today?"},
  {de:"Ja, ich habe viele Videomeetings. Das ist im Büro schwierig.",en:"Yes, I have lots of video meetings. That's difficult in the office."},
  {de:"Verstehe ich. Ich finde Homeoffice manchmal besser, manchmal schlechter.",en:"I understand. I sometimes find home office better, sometimes worse."},
  {de:"Was gefällt dir daran nicht?",en:"What don't you like about it?"},
  {de:"Man vermisst die Kollegen. Und die Trennung zwischen Arbeit und Freizeit fehlt.",en:"You miss the colleagues. And the separation between work and leisure time is missing."},
  {de:"Das stimmt. Ich setze mir feste Arbeitszeiten, das hilft.",en:"That's true. I set fixed working hours for myself, that helps."},
  {de:"Gute Idee. Ich versuche das auch, aber es klappt nicht immer.",en:"Good idea. I try that too, but it doesn't always work."},
]},
{id:"work-6",title:"Networking Event",category:"Work",level:"B2",exchanges:[
  {de:"Guten Abend! Sind Sie auch zum ersten Mal bei dieser Veranstaltung?",en:"Good evening! Is this also your first time at this event?"},
  {de:"Ja, tatsächlich. Kennen Sie jemanden hier?",en:"Yes, actually. Do you know anyone here?"},
  {de:"Ein paar Leute vom letzten Jahr. Was machen Sie beruflich?",en:"A few people from last year. What do you do professionally?"},
  {de:"Ich bin Softwareentwicklerin bei einer Berliner Startup-Firma.",en:"I'm a software developer at a Berlin startup."},
  {de:"Interessant! In welchem Bereich?",en:"Interesting! In which area?"},
  {de:"Wir entwickeln KI-Lösungen für kleine und mittelständische Unternehmen.",en:"We develop AI solutions for small and medium-sized companies."},
  {de:"Das klingt spannend. Ich bin im Bereich Digital Marketing tätig.",en:"That sounds exciting. I work in digital marketing."},
  {de:"Da gibt es sicher Überschneidungen. Darf ich Ihre Visitenkarte haben?",en:"There are certainly overlaps there. May I have your business card?"},
  {de:"Natürlich. Hier bitte. Und Ihre?",en:"Of course. Here you go. And yours?"},
]},

// ═══════════════════════════════════════════════════════
//  HOUSING
// ═══════════════════════════════════════════════════════
{id:"house-1",title:"Apartment Viewing",category:"Housing",level:"B1",exchanges:[
  {de:"Hallo, ich komme wegen der Wohnungsbesichtigung.",en:"Hello, I'm here about the apartment viewing."},
  {de:"Ah ja, schön. Kommen Sie rein.",en:"Ah yes, great. Come in."},
  {de:"Die Wohnung ist sehr schön! Wie groß ist sie?",en:"The apartment is very nice! How big is it?"},
  {de:"65 Quadratmeter. Zwei Schlafzimmer und ein Wohnzimmer.",en:"65 square metres. Two bedrooms and a living room."},
  {de:"Und was kostet die Miete?",en:"And what does the rent cost?"},
  {de:"900 Euro kalt. Mit Nebenkosten ungefähr 1100 Euro.",en:"900 euros without utilities. With utilities about 1100 euros."},
  {de:"Ist das Parken im Preis inbegriffen?",en:"Is parking included in the price?"},
  {de:"Nein, ein Stellplatz kostet 50 Euro extra.",en:"No, a parking space costs 50 euros extra."},
  {de:"Wann wäre die Wohnung frei?",en:"When would the apartment be free?"},
  {de:"Ab dem ersten nächsten Monat.",en:"From the first of next month."},
  {de:"Sehr schön. Ich überlege es mir und melde mich.",en:"Very nice. I'll think it over and get in touch."},
]},
{id:"house-2",title:"Problem with Landlord",category:"Housing",level:"B2",exchanges:[
  {de:"Guten Tag, hier ist Thomas Müller aus der Wohnung 3.",en:"Good day, this is Thomas Müller from flat 3."},
  {de:"Ja, Herr Müller? Was kann ich für Sie tun?",en:"Yes, Mr Müller? What can I do for you?"},
  {de:"Ich habe seit einer Woche ein Problem mit der Heizung.",en:"I've had a problem with the heating for a week."},
  {de:"Was genau ist das Problem?",en:"What exactly is the problem?"},
  {de:"Die Heizung in meinem Schlafzimmer funktioniert nicht.",en:"The heating in my bedroom isn't working."},
  {de:"Haben Sie schon am Thermostat gedreht?",en:"Have you already adjusted the thermostat?"},
  {de:"Ja natürlich. Das Problem liegt woanders.",en:"Yes of course. The problem is elsewhere."},
  {de:"Ich schicke morgen einen Techniker vorbei.",en:"I'll send a technician round tomorrow."},
  {de:"Wann ungefähr? Ich bin nachmittags zu Hause.",en:"Roughly when? I'm home in the afternoon."},
  {de:"Zwischen 14 und 16 Uhr, wenn das passt.",en:"Between 2 and 4 pm, if that's convenient."},
  {de:"Das passt. Ich erwarte ihn.",en:"That's fine. I'll expect him."},
]},
{id:"house-3",title:"Moving In",category:"Housing",level:"B1",exchanges:[
  {de:"Herzlichen Glückwunsch zur neuen Wohnung!",en:"Congratulations on the new apartment!"},
  {de:"Danke! Ich bin total aufgeregt.",en:"Thank you! I'm totally excited."},
  {de:"Wann kannst du einziehen?",en:"When can you move in?"},
  {de:"Nächsten Samstag. Kannst du mir beim Umzug helfen?",en:"Next Saturday. Can you help me move?"},
  {de:"Klar! Brauchst du einen Transporter?",en:"Of course! Do you need a van?"},
  {de:"Ja, das wäre super. Ich habe nicht so viele Möbel.",en:"Yes, that would be great. I don't have that many pieces of furniture."},
  {de:"Ich frage meinen Bruder. Er hat einen Anhänger.",en:"I'll ask my brother. He has a trailer."},
  {de:"Das wäre toll. Ich gebe natürlich Pizza und Bier aus!",en:"That would be great. I'll provide pizza and beer of course!"},
  {de:"Deal! Um wie viel Uhr sollen wir kommen?",en:"Deal! What time should we come?"},
  {de:"Am besten um 9 Uhr morgens.",en:"9 o'clock in the morning would be best."},
]},

// ═══════════════════════════════════════════════════════
//  EDUCATION & LEARNING
// ═══════════════════════════════════════════════════════
{id:"edu-1",title:"At a Language School",category:"Education",level:"A2",exchanges:[
  {de:"Guten Morgen! Ich interessiere mich für einen Deutschkurs.",en:"Good morning! I'm interested in a German course."},
  {de:"Herzlich willkommen! Welches Niveau haben Sie?",en:"Welcome! What level do you have?"},
  {de:"Ich bin Anfänger. Ich lerne seit zwei Monaten alleine.",en:"I'm a beginner. I've been learning alone for two months."},
  {de:"Dann empfehle ich Ihnen den A1-Kurs.",en:"Then I recommend the A1 course for you."},
  {de:"Wann findet der statt?",en:"When does it take place?"},
  {de:"Dienstags und donnerstags von 18 bis 20 Uhr.",en:"Tuesdays and Thursdays from 6 to 8 pm."},
  {de:"Das passt gut. Wie viele Teilnehmer hat der Kurs?",en:"That works well. How many participants does the course have?"},
  {de:"Maximal zwölf. So kann jeder genug üben.",en:"A maximum of twelve. That way everyone can practise enough."},
  {de:"Was kostet der Kurs?",en:"What does the course cost?"},
  {de:"180 Euro für zehn Wochen. Inklusive Lehrmaterial.",en:"180 euros for ten weeks. Including teaching materials."},
]},
{id:"edu-2",title:"Discussing University",category:"Education",level:"B1",exchanges:[
  {de:"Was studierst du?",en:"What are you studying?"},
  {de:"Ich studiere Informatik im dritten Semester.",en:"I'm studying computer science in my third semester."},
  {de:"Das ist interessant. Macht es dir Spaß?",en:"That's interesting. Do you enjoy it?"},
  {de:"Ja, sehr! Aber es ist auch anspruchsvoll.",en:"Yes, very much! But it's also demanding."},
  {de:"Was ist das Schwerste daran?",en:"What is the hardest part of it?"},
  {de:"Die Mathematikkurse. Die sind wirklich intensiv.",en:"The maths courses. They're really intensive."},
  {de:"Was möchtest du später damit machen?",en:"What do you want to do with it later?"},
  {de:"Ich würde gerne in der Spieleentwicklung arbeiten.",en:"I'd like to work in game development."},
  {de:"Cool! Das klingt nach einem Traumjob.",en:"Cool! That sounds like a dream job."},
]},
{id:"edu-3",title:"Helping with Homework",category:"Education",level:"A2",exchanges:[
  {de:"Mama, kannst du mir bei den Hausaufgaben helfen?",en:"Mum, can you help me with my homework?"},
  {de:"Natürlich. Was hast du auf?",en:"Of course. What do you have to do?"},
  {de:"Ich verstehe diese Matheaufgabe nicht.",en:"I don't understand this maths problem."},
  {de:"Zeig mal. Ah, das ist eine Gleichung. Hast du das in der Schule behandelt?",en:"Let me see. Ah, that's an equation. Have you covered that at school?"},
  {de:"Ja, aber ich habe es nicht verstanden.",en:"Yes, but I didn't understand it."},
  {de:"Kein Problem. Lass mich es dir erklären.",en:"No problem. Let me explain it to you."},
  {de:"Okay. Und kannst du danach auch mein Deutsch kontrollieren?",en:"Okay. And can you check my German afterwards too?"},
  {de:"Natürlich. Aber zuerst die Mathe!",en:"Of course. But maths first!"},
]},

// ═══════════════════════════════════════════════════════
//  SOCIAL SITUATIONS
// ═══════════════════════════════════════════════════════
{id:"social-1",title:"At a Party",category:"Social",level:"A2",exchanges:[
  {de:"Hi! Ich heiße Sebastian. Kennst du hier viele Leute?",en:"Hi! I'm Sebastian. Do you know many people here?"},
  {de:"Nicht so viele. Nur den Gastgeber.",en:"Not that many. Just the host."},
  {de:"Das geht mir genauso! Woher kennst du Klaus?",en:"Same here! How do you know Klaus?"},
  {de:"Wir haben zusammen studiert. Und du?",en:"We studied together. And you?"},
  {de:"Wir arbeiten im selben Büro.",en:"We work in the same office."},
  {de:"Aha, interessant! Was machst du beruflich?",en:"Interesting! What do you do for work?"},
  {de:"Ich bin Grafiker. Und du?",en:"I'm a graphic designer. And you?"},
  {de:"Ich arbeite im Bereich Marketing.",en:"I work in marketing."},
  {de:"Oh, wir könnten mal zusammenarbeiten! (lacht)",en:"Oh, we could work together sometime! (laughs)"},
]},
{id:"social-2",title:"Inviting Someone",category:"Social",level:"A2",exchanges:[
  {de:"Wir machen am Samstag eine Geburtstagsparty. Kommst du?",en:"We're having a birthday party on Saturday. Will you come?"},
  {de:"Oh, wer hat Geburtstag?",en:"Oh, whose birthday is it?"},
  {de:"Mein Freund Thomas wird 30.",en:"My friend Thomas is turning 30."},
  {de:"Das ist ein besonderer Anlass! Wie viele Leute kommen?",en:"That's a special occasion! How many people are coming?"},
  {de:"Ungefähr zwanzig. Es wird gemütlich.",en:"About twenty. It'll be cosy."},
  {de:"Klingt toll! Wo findet es statt?",en:"Sounds great! Where is it taking place?"},
  {de:"Bei uns zu Hause. Wir haben eine große Wohnung.",en:"At our place. We have a big flat."},
  {de:"Soll ich etwas mitbringen?",en:"Shall I bring something?"},
  {de:"Ein Dessert oder eine Flasche Wein wäre toll.",en:"A dessert or a bottle of wine would be lovely."},
  {de:"Mache ich! Bis Samstag!",en:"Will do! See you Saturday!"},
]},
{id:"social-3",title:"Apologising",category:"Social",level:"A2",exchanges:[
  {de:"Oh Entschuldigung! Ich habe nicht aufgepasst.",en:"Oh sorry! I wasn't paying attention."},
  {de:"Kein Problem. Ist Ihnen etwas passiert?",en:"No problem. Did anything happen to you?"},
  {de:"Nein, nein. Alles gut. Tut mir wirklich leid.",en:"No, no. Everything's fine. I'm really sorry."},
  {de:"Machen Sie sich keine Sorgen. Es ist nichts.",en:"Don't worry. It's nothing."},
  {de:"Trotzdem, es war meine Schuld.",en:"Even so, it was my fault."},
  {de:"Wirklich, alles gut. Passen Sie beim nächsten Mal einfach auf.",en:"Really, everything's fine. Just be careful next time."},
  {de:"Versprochen! Und nochmals Entschuldigung.",en:"Promised! And sorry again."},
]},
{id:"social-4",title:"Planning a Trip Together",category:"Social",level:"B1",exchanges:[
  {de:"Wollen wir dieses Jahr zusammen verreisen?",en:"Do you want to travel together this year?"},
  {de:"Oh ja! Das wäre super. Wohin?",en:"Oh yes! That would be great. Where to?"},
  {de:"Ich dachte an Süditalien. Was hältst du davon?",en:"I was thinking of southern Italy. What do you think?"},
  {de:"Tolle Idee! Wann hast du Urlaub?",en:"Great idea! When do you have holidays?"},
  {de:"Im August. Zwei Wochen.",en:"In August. Two weeks."},
  {de:"Das passt mir auch. Wie wollen wir hinfliegen?",en:"That suits me too. How do we want to get there?"},
  {de:"Günstige Flüge wären am besten. Ich schaue mal.",en:"Cheap flights would be best. I'll have a look."},
  {de:"Gut. Und wohnen wir in einem Hotel oder AirBnB?",en:"Good. And are we staying in a hotel or AirBnB?"},
  {de:"AirBnB ist oft günstiger und gemütlicher.",en:"AirBnB is often cheaper and cosier."},
  {de:"Einverstanden! Ich freue mich schon!",en:"Agreed! I'm already looking forward to it!"},
]},
{id:"social-5",title:"Discussing a Film",category:"Social",level:"B1",exchanges:[
  {de:"Hast du den neuen Film von Nolan gesehen?",en:"Have you seen the new Nolan film?"},
  {de:"Nein, noch nicht. Wie war er?",en:"No, not yet. How was it?"},
  {de:"Absolut beeindruckend. Aber sehr komplex.",en:"Absolutely impressive. But very complex."},
  {de:"Das sagt man über alle seine Filme.",en:"They say that about all his films."},
  {de:"Stimmt. Aber diesmal hat er sich wirklich übertroffen.",en:"True. But this time he really surpassed himself."},
  {de:"Was gefiel dir am besten?",en:"What did you like best?"},
  {de:"Die Kameraarbeit und die Musik waren außergewöhnlich.",en:"The cinematography and the music were extraordinary."},
  {de:"Ich muss ihn mir unbedingt anschauen.",en:"I really must watch it."},
  {de:"Am besten im Kino. Im Heimkino verliert er etwas.",en:"In the cinema is best. At home it loses something."},
]},
{id:"social-6",title:"Giving a Compliment",category:"Social",level:"A2",exchanges:[
  {de:"Wow, ich liebe deinen Pullover! Wo hast du den her?",en:"Wow, I love your jumper! Where did you get it?"},
  {de:"Oh danke! Ich habe ihn im Secondhand-Laden gefunden.",en:"Oh thank you! I found it in a secondhand shop."},
  {de:"Wirklich? Der sieht neu aus!",en:"Really? It looks new!"},
  {de:"Ja, kaum getragen. Für nur fünf Euro!",en:"Yes, barely worn. For only five euros!"},
  {de:"Das ist ein Schnäppchen! Ich gehe da auch mal hin.",en:"That's a bargain! I'll go there sometime too."},
  {de:"Es lohnt sich wirklich. Man findet dort tolle Sachen.",en:"It's really worth it. You find great things there."},
  {de:"Super Tipp. Danke!",en:"Great tip. Thanks!"},
]},

// ═══════════════════════════════════════════════════════
//  TELEPHONE & DIGITAL
// ═══════════════════════════════════════════════════════
{id:"phone-1",title:"Making a Phone Call",category:"Telephone",level:"A2",exchanges:[
  {de:"Hallo, hier ist Anna Schmidt.",en:"Hello, this is Anna Schmidt."},
  {de:"Guten Tag, Frau Schmidt. Was kann ich für Sie tun?",en:"Good day, Ms Schmidt. What can I do for you?"},
  {de:"Ich möchte einen Termin vereinbaren.",en:"I'd like to arrange an appointment."},
  {de:"Natürlich. Wofür brauchen Sie den Termin?",en:"Of course. What do you need the appointment for?"},
  {de:"Ich möchte mein Konto eröffnen.",en:"I'd like to open an account."},
  {de:"Haben Sie am Donnerstag um 14 Uhr Zeit?",en:"Do you have time on Thursday at 2 pm?"},
  {de:"Ja, das passt sehr gut.",en:"Yes, that suits me very well."},
  {de:"Schön. Bringen Sie bitte Ihren Personalausweis mit.",en:"Great. Please bring your ID card with you."},
  {de:"Mache ich. Danke und auf Wiederhören!",en:"Will do. Thank you and goodbye!"},
]},
{id:"phone-2",title:"Leaving a Voicemail",category:"Telephone",level:"B1",exchanges:[
  {de:"Hier ist der Anrufbeantworter von Dr. Braun. Bitte hinterlassen Sie eine Nachricht.",en:"This is Dr Braun's answerphone. Please leave a message."},
  {de:"Guten Tag, hier ist Klaus Weiß. Ich rufe wegen meines Termins am Freitag an.",en:"Good day, this is Klaus Weiss. I'm calling about my appointment on Friday."},
  {de:"Leider muss ich den Termin absagen. Ich bin krank geworden.",en:"Unfortunately I have to cancel the appointment. I've fallen ill."},
  {de:"Ich würde gerne einen neuen Termin vereinbaren. Bitte rufen Sie mich zurück.",en:"I'd like to arrange a new appointment. Please call me back."},
  {de:"Meine Nummer ist 0178-4521893. Vielen Dank!",en:"My number is 0178-4521893. Many thanks!"},
]},
{id:"phone-3",title:"Bad Connection",category:"Telephone",level:"A2",exchanges:[
  {de:"Hallo? Bist du noch da?",en:"Hello? Are you still there?"},
  {de:"Ja, ich bin da. Ich höre dich kaum.",en:"Yes, I'm here. I can barely hear you."},
  {de:"Die Verbindung ist sehr schlecht.",en:"The connection is very bad."},
  {de:"Ich höre viel Rauschen. Geh mal ein bisschen zur Seite.",en:"I hear lots of noise. Move over a bit."},
  {de:"Jetzt besser?",en:"Better now?"},
  {de:"Ja, ein bisschen. Was hast du gerade gesagt?",en:"Yes, a little. What did you just say?"},
  {de:"Ich habe gefragt, wann du nach Hause kommst.",en:"I asked when you're coming home."},
  {de:"Gegen sieben Uhr. Ich bin gleich fertig.",en:"Around seven o'clock. I'm nearly done."},
]},

// ═══════════════════════════════════════════════════════
//  BANKING & OFFICIAL MATTERS
// ═══════════════════════════════════════════════════════
{id:"bank-1",title:"At the Bank",category:"Banking",level:"B1",exchanges:[
  {de:"Guten Tag. Ich möchte ein Konto eröffnen.",en:"Good day. I'd like to open an account."},
  {de:"Herzlich willkommen. Was für ein Konto?",en:"Welcome. What kind of account?"},
  {de:"Ein normales Girokonto für den Alltag.",en:"A normal current account for everyday use."},
  {de:"Haben Sie Ihren Personalausweis dabei?",en:"Do you have your ID card with you?"},
  {de:"Ja, hier ist er.",en:"Yes, here it is."},
  {de:"Danke. Sind Sie in Deutschland gemeldet?",en:"Thank you. Are you registered in Germany?"},
  {de:"Ja, ich wohne seit einem Jahr in Berlin.",en:"Yes, I've been living in Berlin for a year."},
  {de:"Gut. Haben Sie eine Steuernummer?",en:"Good. Do you have a tax number?"},
  {de:"Ja, ich habe sie letzte Woche bekommen.",en:"Yes, I received it last week."},
  {de:"Perfekt. Dann können wir direkt anfangen.",en:"Perfect. Then we can start right away."},
]},
{id:"bank-2",title:"Reporting a Lost Card",category:"Banking",level:"B1",exchanges:[
  {de:"Guten Tag, ich glaube, meine Bankkarte wurde gestohlen.",en:"Good day, I think my bank card has been stolen."},
  {de:"Oh nein! Wann haben Sie das bemerkt?",en:"Oh no! When did you notice?"},
  {de:"Vor einer Stunde. Ich habe sie überall gesucht.",en:"An hour ago. I've looked everywhere for it."},
  {de:"Ich sperre die Karte sofort. Haben Sie Ihre Kontonummer?",en:"I'll block the card immediately. Do you have your account number?"},
  {de:"Ja, die habe ich hier.",en:"Yes, I have it here."},
  {de:"Gut. Haben Sie Ihre PIN mit jemand geteilt?",en:"Good. Have you shared your PIN with anyone?"},
  {de:"Nein, niemals.",en:"No, never."},
  {de:"Prima. Die Karte ist jetzt gesperrt. Wann möchten Sie eine neue?",en:"Good. The card is now blocked. When would you like a new one?"},
  {de:"So schnell wie möglich, bitte.",en:"As soon as possible, please."},
  {de:"In drei bis fünf Werktagen bekommen Sie eine neue Karte.",en:"You'll receive a new card in three to five working days."},
]},

// ═══════════════════════════════════════════════════════
//  EXPRESSING OPINIONS & FEELINGS
// ═══════════════════════════════════════════════════════
{id:"opinion-1",title:"Agreeing and Disagreeing",category:"Expressions",level:"B1",exchanges:[
  {de:"Ich finde, dass wir zu viel Zeit mit Smartphones verbringen.",en:"I think we spend too much time on smartphones."},
  {de:"Da bin ich ganz deiner Meinung.",en:"I completely agree with you."},
  {de:"Das ruiniert echte menschliche Beziehungen.",en:"It ruins real human relationships."},
  {de:"Da bin ich nicht so sicher. Es verbindet uns auch.",en:"I'm not so sure about that. It also connects us."},
  {de:"Ja, aber nicht auf echte Weise.",en:"Yes, but not in a real way."},
  {de:"Kommt drauf an, wie man es nutzt.",en:"It depends on how you use it."},
  {de:"Das stimmt. Man muss einen guten Umgang damit finden.",en:"That's true. You have to find a good way of dealing with it."},
  {de:"Genau. Es ist Werkzeug, kein Feind.",en:"Exactly. It's a tool, not an enemy."},
]},
{id:"opinion-2",title:"Giving Your Opinion Politely",category:"Expressions",level:"B2",exchanges:[
  {de:"Was halten Sie von der neuen Politik?",en:"What do you think of the new policy?"},
  {de:"Ehrlich gesagt bin ich etwas skeptisch.",en:"Honestly I'm a little sceptical."},
  {de:"Was meinen Sie damit?",en:"What do you mean by that?"},
  {de:"Ich glaube, die Maßnahmen gehen nicht weit genug.",en:"I think the measures don't go far enough."},
  {de:"Das sehe ich etwas anders. Die Schritte sind ein guter Anfang.",en:"I see that a little differently. The steps are a good start."},
  {de:"Vielleicht haben Sie recht. Ich bin zu ungeduldig.",en:"Maybe you're right. I'm too impatient."},
  {de:"Es ist wichtig, kritisch zu sein. Aber man muss auch fair sein.",en:"It's important to be critical. But you also have to be fair."},
  {de:"Da haben Sie absolut recht.",en:"You're absolutely right there."},
]},
{id:"opinion-3",title:"Complaining Politely",category:"Expressions",level:"B1",exchanges:[
  {de:"Ich möchte mich über etwas beschweren.",en:"I'd like to complain about something."},
  {de:"Was ist das Problem?",en:"What's the problem?"},
  {de:"Ich warte jetzt seit 40 Minuten. Das ist zu lang.",en:"I've been waiting for 40 minutes now. That's too long."},
  {de:"Es tut mir sehr leid. Wir haben heute viele Kunden.",en:"I'm very sorry. We have many customers today."},
  {de:"Das verstehe ich, aber eine Information wäre nett gewesen.",en:"I understand that, but some information would have been nice."},
  {de:"Sie haben vollkommen recht. Das war unser Fehler.",en:"You're absolutely right. That was our mistake."},
  {de:"Ich würde nur gerne wissen, wie lange es noch dauert.",en:"I'd just like to know how much longer it will be."},
  {de:"Noch etwa zehn Minuten. Kann ich Ihnen einen Kaffee anbieten?",en:"About another ten minutes. Can I offer you a coffee?"},
  {de:"Das wäre sehr nett. Danke.",en:"That would be very kind. Thank you."},
]},
{id:"opinion-4",title:"Expressing Surprise",category:"Expressions",level:"A2",exchanges:[
  {de:"Du glaubst das nicht — ich habe in der Lotterie gewonnen!",en:"You won't believe it — I won the lottery!"},
  {de:"Wirklich?! Das ist unglaublich!",en:"Really?! That's unbelievable!"},
  {de:"Ja! 5000 Euro!",en:"Yes! 5000 euros!"},
  {de:"Das ist ja wahnsinnig! Was machst du damit?",en:"That's incredible! What are you going to do with it?"},
  {de:"Ich weiß noch nicht. Vielleicht eine Reise.",en:"I don't know yet. Maybe a trip."},
  {de:"Oh, das wäre toll! Wohin würdest du fahren?",en:"Oh, that would be great! Where would you go?"},
  {de:"Japan steht schon lange auf meiner Liste.",en:"Japan has been on my list for a long time."},
  {de:"Perfekte Wahl! Ich bin so eifersüchtig!",en:"Perfect choice! I'm so jealous!"},
]},
{id:"opinion-5",title:"Encouraging Someone",category:"Expressions",level:"A2",exchanges:[
  {de:"Ich habe morgen eine wichtige Prüfung und bin total nervös.",en:"I have an important exam tomorrow and I'm totally nervous."},
  {de:"Das verstehe ich. Hast du viel gelernt?",en:"I understand. Have you studied a lot?"},
  {de:"Ja, aber ich glaube, ich bin nicht gut genug.",en:"Yes, but I think I'm not good enough."},
  {de:"Du bist zu streng mit dir! Du bist sehr gut vorbereitet.",en:"You're too hard on yourself! You're very well prepared."},
  {de:"Glaubst du wirklich?",en:"Do you really think so?"},
  {de:"Absolut! Ich habe gesehen, wie viel du gearbeitet hast.",en:"Absolutely! I've seen how much you've worked."},
  {de:"Danke, das hilft wirklich.",en:"Thank you, that really helps."},
  {de:"Mach dir keine Sorgen. Du schaffst das!",en:"Don't worry. You can do it!"},
]},

// ═══════════════════════════════════════════════════════
//  WEATHER & ENVIRONMENT
// ═══════════════════════════════════════════════════════
{id:"weather-1",title:"Weather Forecast",category:"Environment",level:"A2",exchanges:[
  {de:"Wie wird das Wetter morgen?",en:"What will the weather be like tomorrow?"},
  {de:"Laut Vorhersage regnet es den ganzen Tag.",en:"According to the forecast, it will rain all day."},
  {de:"Oh nein. Wir wollten picknicken.",en:"Oh no. We wanted to have a picnic."},
  {de:"Das können wir verschieben. Übermorgen soll es schön sein.",en:"We can postpone it. The day after tomorrow it's supposed to be nice."},
  {de:"Gut. Und wie kalt wird es morgen?",en:"Good. And how cold will it be tomorrow?"},
  {de:"Um die zwölf Grad. Ziemlich frisch.",en:"Around twelve degrees. Quite fresh."},
  {de:"Ich brauche auf jeden Fall eine Jacke.",en:"I'll definitely need a jacket."},
  {de:"Ja, und einen Regenschirm wäre auch nicht schlecht.",en:"Yes, and an umbrella wouldn't be bad either."},
]},
{id:"weather-2",title:"Talking About Climate Change",category:"Environment",level:"B2",exchanges:[
  {de:"Hast du die neuesten Nachrichten zum Klimawandel gelesen?",en:"Have you read the latest news on climate change?"},
  {de:"Ja, die Situation ist wirklich besorgniserregend.",en:"Yes, the situation is really worrying."},
  {de:"Was glaubst du, können wir persönlich tun?",en:"What do you think can we personally do?"},
  {de:"Weniger fliegen, weniger Fleisch essen, öffentliche Verkehrsmittel nutzen.",en:"Fly less, eat less meat, use public transport."},
  {de:"Das stimmt. Aber ist das wirklich genug?",en:"That's true. But is that really enough?"},
  {de:"Nein, ohne politische Veränderungen nicht.",en:"No, not without political changes."},
  {de:"Genau. Wir brauchen systemische Lösungen.",en:"Exactly. We need systemic solutions."},
  {de:"Ich finde, man muss beides tun: persönlich handeln UND politisch aktiv sein.",en:"I think you have to do both: act personally AND be politically active."},
  {de:"Da stimme ich dir zu. Kleiner Anfang, großes Ziel.",en:"I agree with you. Small start, big goal."},
]},

// ═══════════════════════════════════════════════════════
//  FOOD & COOKING
// ═══════════════════════════════════════════════════════
{id:"food-1",title:"Sharing a Recipe",category:"Food",level:"B1",exchanges:[
  {de:"Dein Kuchen war fantastisch! Wie machst du das?",en:"Your cake was fantastic! How do you make it?"},
  {de:"Oh danke! Es ist eigentlich ganz einfach.",en:"Oh thank you! It's actually quite simple."},
  {de:"Wirklich? Ich kann überhaupt nicht backen.",en:"Really? I can't bake at all."},
  {de:"Das lernst du. Was brauchst du: Mehl, Zucker, Butter, Eier...",en:"You can learn it. What you need: flour, sugar, butter, eggs..."},
  {de:"Und was noch?",en:"And what else?"},
  {de:"Backpulver und etwas Vanille. Das ist alles.",en:"Baking powder and some vanilla. That's all."},
  {de:"Und wie lange muss er backen?",en:"And how long does it have to bake?"},
  {de:"Bei 180 Grad etwa 45 Minuten.",en:"At 180 degrees for about 45 minutes."},
  {de:"Das klingt machbar. Darf ich das Rezept haben?",en:"That sounds doable. May I have the recipe?"},
  {de:"Natürlich! Ich schicke es dir per WhatsApp.",en:"Of course! I'll send it to you on WhatsApp."},
]},
{id:"food-2",title:"Dietary Preferences",category:"Food",level:"B1",exchanges:[
  {de:"Isst du alles? Ich plane ein Abendessen.",en:"Do you eat everything? I'm planning a dinner."},
  {de:"Ich bin Vegetarierin. Aber ich esse Fisch und Käse.",en:"I'm vegetarian. But I eat fish and cheese."},
  {de:"Okay, das ist kein Problem. Irgendwelche Allergien?",en:"Okay, that's no problem. Any allergies?"},
  {de:"Ja, ich bin gegen Nüsse allergisch. Das ist wichtig.",en:"Yes, I'm allergic to nuts. That's important."},
  {de:"Oh, danke dass du es sagst! Das beachte ich.",en:"Oh, thanks for saying so! I'll take note of that."},
  {de:"Und isst dein Partner auch kein Fleisch?",en:"And does your partner also not eat meat?"},
  {de:"Doch, er isst alles. Aber er mag keinen Fisch.",en:"Yes, he eats everything. But he doesn't like fish."},
  {de:"Verstanden. Dann mache ich ein vegetarisches Hauptgericht.",en:"Understood. Then I'll make a vegetarian main course."},
  {de:"Das ist so nett! Wir freuen uns.",en:"That's so kind! We're looking forward to it."},
]},

// ═══════════════════════════════════════════════════════
//  HOBBIES & SPORTS
// ═══════════════════════════════════════════════════════
{id:"hobby-1",title:"Discussing Sports",category:"Hobbies",level:"A2",exchanges:[
  {de:"Treibst du Sport?",en:"Do you do sport?"},
  {de:"Ja, ich schwimme zweimal die Woche.",en:"Yes, I swim twice a week."},
  {de:"Das ist toll! Wo schwimmst du?",en:"That's great! Where do you swim?"},
  {de:"Im Freibad im Sommer, im Hallenbad im Winter.",en:"In the outdoor pool in summer, in the indoor pool in winter."},
  {de:"Das ist sehr konsequent. Magst du keinen anderen Sport?",en:"That's very consistent. Don't you like any other sport?"},
  {de:"Ich jogge manchmal auch. Aber nicht so regelmäßig.",en:"I also jog sometimes. But not as regularly."},
  {de:"Ich spiele Fußball mit Freunden. Das macht viel Spaß.",en:"I play football with friends. That's a lot of fun."},
  {de:"Fußball! Das habe ich als Kind gespielt.",en:"Football! I played that as a child."},
]},
{id:"hobby-2",title:"Music",category:"Hobbies",level:"A2",exchanges:[
  {de:"Hörst du gerne Musik?",en:"Do you like listening to music?"},
  {de:"Ja, sehr! Am liebsten höre ich Jazz.",en:"Yes, very much! I like listening to jazz best."},
  {de:"Jazz? Das höre ich auch gerne.",en:"Jazz? I like that too."},
  {de:"Wirklich? Was für Jazz? Modern oder klassisch?",en:"Really? What kind of jazz? Modern or classic?"},
  {de:"Eher klassisch. Coltrane, Miles Davis...",en:"Rather classic. Coltrane, Miles Davis..."},
  {de:"Oh, ich kenne Coltrane gut. 'A Love Supreme' ist ein Meisterwerk.",en:"Oh, I know Coltrane well. 'A Love Supreme' is a masterpiece."},
  {de:"Absolut! Spielst du selbst ein Instrument?",en:"Absolutely! Do you play an instrument yourself?"},
  {de:"Ich spiele Gitarre. Nicht professionell, aber ich mache es gerne.",en:"I play guitar. Not professionally, but I enjoy it."},
  {de:"Das ist wunderschön. Hast du dir das selbst beigebracht?",en:"That's wonderful. Did you teach yourself?"},
]},

// ═══════════════════════════════════════════════════════
//  TRAVEL & TOURISM
// ═══════════════════════════════════════════════════════
{id:"travel-1",title:"At the Hotel Check-in",category:"Travel",level:"A2",exchanges:[
  {de:"Guten Abend! Ich habe eine Reservierung.",en:"Good evening! I have a reservation."},
  {de:"Auf welchen Namen bitte?",en:"Under which name please?"},
  {de:"Miller, Thomas Miller.",en:"Miller, Thomas Miller."},
  {de:"Einen Moment bitte... Ah ja, hier. Ein Doppelzimmer für drei Nächte.",en:"One moment please... Ah yes, here. A double room for three nights."},
  {de:"Genau. Mit Frühstück inklusive.",en:"Exactly. With breakfast included."},
  {de:"Ja, Frühstück ist von 7 bis 10 Uhr.",en:"Yes, breakfast is from 7 to 10 o'clock."},
  {de:"Und wo ist das Zimmer?",en:"And where is the room?"},
  {de:"Im dritten Stock, Zimmer 312. Hier ist Ihre Schlüsselkarte.",en:"On the third floor, room 312. Here is your key card."},
  {de:"Danke. Haben Sie auch WLAN?",en:"Thank you. Do you have WiFi too?"},
  {de:"Ja, gratis. Das Passwort ist auf der Karte.",en:"Yes, free. The password is on the card."},
]},
{id:"travel-2",title:"Asking About Tourist Attractions",category:"Travel",level:"A2",exchanges:[
  {de:"Entschuldigung, wir sind zum ersten Mal in Berlin. Was sollten wir unbedingt sehen?",en:"Excuse me, we're in Berlin for the first time. What should we definitely see?"},
  {de:"Oh, da gibt es so viel! Das Brandenburger Tor ist ein Muss.",en:"Oh, there's so much! The Brandenburg Gate is a must."},
  {de:"Ist es weit von hier?",en:"Is it far from here?"},
  {de:"Nein, etwa zehn Minuten zu Fuß.",en:"No, about ten minutes on foot."},
  {de:"Und was noch?",en:"And what else?"},
  {de:"Das Holocaust-Denkmal liegt gleich daneben. Sehr eindrucksvoll.",en:"The Holocaust Memorial is right next to it. Very impressive."},
  {de:"Was würden Sie zum Mittagessen empfehlen?",en:"What would you recommend for lunch?"},
  {de:"Probieren Sie unbedingt einen Döner oder Currywurst. Das ist typisch Berlin.",en:"Definitely try a döner or currywurst. That's typical Berlin."},
  {de:"Currywurst kenne ich! Die habe ich schon probiert.",en:"I know currywurst! I've already tried it."},
]},
{id:"travel-3",title:"Lost in the City",category:"Travel",level:"B1",exchanges:[
  {de:"Entschuldigung, ich glaube, ich habe mich verlaufen.",en:"Excuse me, I think I've got lost."},
  {de:"Kein Problem. Wo möchten Sie hin?",en:"No problem. Where do you want to go?"},
  {de:"Zum Hauptbahnhof. Ich finde es nicht auf meiner Karte.",en:"To the main station. I can't find it on my map."},
  {de:"Der ist nicht weit. Gehen Sie diese Straße lang bis zum Ende.",en:"It's not far. Go along this street to the end."},
  {de:"Und dann?",en:"And then?"},
  {de:"Dann sehen Sie schon das Gebäude. Es hat einen großen Glasturm.",en:"Then you'll see the building. It has a large glass tower."},
  {de:"Ah, super! Und wie lange dauert das?",en:"Ah, great! And how long does that take?"},
  {de:"Vielleicht sieben bis zehn Minuten. Hören Sie das an?",en:"Maybe seven to ten minutes. Is that all right?"},
  {de:"Ja, das ist prima. Vielen Dank für Ihre Hilfe!",en:"Yes, that's great. Many thanks for your help!"},
  {de:"Gern! Ich hoffe, Sie finden es gut.",en:"You're welcome! I hope you have a good time."},
]},

// ═══════════════════════════════════════════════════════
//  DISAGREEMENT & CONFLICT
// ═══════════════════════════════════════════════════════
{id:"conflict-1",title:"Resolving a Misunderstanding",category:"Conflict",level:"B1",exchanges:[
  {de:"Ich glaube, wir haben uns missverstanden.",en:"I think we've misunderstood each other."},
  {de:"Was meinst du damit?",en:"What do you mean by that?"},
  {de:"Ich dachte, wir treffen uns um drei, nicht um vier.",en:"I thought we were meeting at three, not four."},
  {de:"Ach so! Nein, ich hatte eindeutig vier Uhr gesagt.",en:"Oh I see! No, I had clearly said four o'clock."},
  {de:"Dann habe ich es falsch verstanden. Das tut mir leid.",en:"Then I misunderstood. I'm sorry about that."},
  {de:"Kein Problem. Solche Dinge passieren.",en:"No problem. These things happen."},
  {de:"Nächstes Mal schreibe ich alles auf.",en:"Next time I'll write everything down."},
  {de:"Gute Idee. Und ich auch!",en:"Good idea. And me too!"},
]},
{id:"conflict-2",title:"Neighbor Conflict",category:"Conflict",level:"B2",exchanges:[
  {de:"Guten Abend. Ich wohne über Ihnen. Darf ich kurz sprechen?",en:"Good evening. I live above you. May I speak briefly?"},
  {de:"Ja, natürlich. Was ist los?",en:"Yes, of course. What's the matter?"},
  {de:"Die Musik ist seit Stunden sehr laut. Es ist schon 23 Uhr.",en:"The music has been very loud for hours. It's already 11 pm."},
  {de:"Oh, wirklich? Das tut mir leid! Ich hatte nicht bemerkt, wie spät es ist.",en:"Oh, really? I'm sorry! I hadn't noticed how late it is."},
  {de:"Ich muss morgen früh arbeiten und kann nicht schlafen.",en:"I have to work early tomorrow and can't sleep."},
  {de:"Das verstehe ich absolut. Ich stelle die Musik sofort leiser.",en:"I completely understand that. I'll turn the music down immediately."},
  {de:"Das wäre sehr nett. Danke für Ihr Verständnis.",en:"That would be very kind. Thank you for your understanding."},
  {de:"Es tut mir wirklich leid. Das passiert mir nicht wieder.",en:"I'm truly sorry. This won't happen again."},
]},

// ═══════════════════════════════════════════════════════
//  PHILOSOPHY & DEEPER CONVERSATIONS
// ═══════════════════════════════════════════════════════
{id:"deep-1",title:"Talking About Happiness",category:"Philosophy",level:"B2",exchanges:[
  {de:"Was macht dich wirklich glücklich?",en:"What really makes you happy?"},
  {de:"Gute Frage. Wahrscheinlich tiefe Verbindungen mit Menschen.",en:"Good question. Probably deep connections with people."},
  {de:"Nicht Dinge oder Geld?",en:"Not things or money?"},
  {de:"Geld gibt Sicherheit, aber es kauft kein echtes Glück.",en:"Money provides security, but it can't buy real happiness."},
  {de:"Da stimme ich dir zu. Erlebnisse sind wichtiger als Besitz.",en:"I agree with you. Experiences are more important than possessions."},
  {de:"Genau. Ein gutes Gespräch ist mir mehr wert als ein teures Ding.",en:"Exactly. A good conversation is worth more to me than an expensive thing."},
  {de:"Das ist eine schöne Perspektive. Ich versuche, mehr so zu denken.",en:"That's a nice perspective. I try to think more like that."},
  {de:"Es lohnt sich wirklich.",en:"It's really worth it."},
]},
{id:"deep-2",title:"Discussing Work-Life Balance",category:"Philosophy",level:"B2",exchanges:[
  {de:"Findest du es schwierig, Arbeit und Privatleben zu trennen?",en:"Do you find it difficult to separate work and private life?"},
  {de:"Ja, besonders seit ich im Homeoffice arbeite.",en:"Yes, especially since I've been working from home."},
  {de:"Was machst du dagegen?",en:"What do you do about it?"},
  {de:"Ich habe feste Arbeitszeiten und mache danach keinen Laptop mehr auf.",en:"I have fixed working hours and don't open my laptop again afterwards."},
  {de:"Das klingt vernünftig. Schaffst du das wirklich?",en:"That sounds sensible. Do you really manage it?"},
  {de:"Meist ja. Es braucht Disziplin.",en:"Usually yes. It takes discipline."},
  {de:"Ich versuche das auch, aber manchmal ruft das Handy abends noch.",en:"I try that too, but sometimes the phone calls in the evening."},
  {de:"Das musst du konsequent ignorieren. Grenzen setzen ist wichtig.",en:"You have to consistently ignore that. Setting boundaries is important."},
  {de:"Du hast recht. Ich muss da besser werden.",en:"You're right. I need to get better at that."},
]},

// ═══════════════════════════════════════════════════════
//  TECHNOLOGY & MODERN LIFE
// ═══════════════════════════════════════════════════════
{id:"tech-1",title:"Social Media",category:"Technology",level:"B1",exchanges:[
  {de:"Bist du auf sozialen Medien?",en:"Are you on social media?"},
  {de:"Ja, auf Instagram und LinkedIn. Und du?",en:"Yes, on Instagram and LinkedIn. And you?"},
  {de:"Ich nutze sie kaum noch. Es macht mich unruhig.",en:"I barely use them anymore. They make me restless."},
  {de:"Das verstehe ich. Das Scrollen ist wie eine Sucht.",en:"I understand that. Scrolling is like an addiction."},
  {de:"Genau. Ich habe die Apps von meinem Handy gelöscht.",en:"Exactly. I've deleted the apps from my phone."},
  {de:"Wirklich? Wie fühlt sich das an?",en:"Really? How does that feel?"},
  {de:"Ehrlich gesagt, viel besser. Ich habe mehr Zeit und bin ruhiger.",en:"Honestly, much better. I have more time and feel calmer."},
  {de:"Das überlege ich mir auch schon lange.",en:"I've been thinking about that for a long time too."},
]},
{id:"tech-2",title:"Online Shopping",category:"Technology",level:"A2",exchanges:[
  {de:"Kaufst du viel online?",en:"Do you buy a lot online?"},
  {de:"Ja, fast alles. Ich gehe selten in Geschäfte.",en:"Yes, almost everything. I rarely go to shops."},
  {de:"Ist das nicht unpersönlich?",en:"Isn't that impersonal?"},
  {de:"Schon, aber es spart Zeit. Und man vergleicht Preise einfacher.",en:"It is, but it saves time. And you compare prices more easily."},
  {de:"Hast du nie Probleme mit Rücksendungen?",en:"Don't you ever have problems with returns?"},
  {de:"Manchmal. Aber meistens klappt es gut.",en:"Sometimes. But mostly it goes well."},
  {de:"Ich kaufe lieber vor Ort. Man sieht und fühlt das Produkt.",en:"I prefer buying locally. You can see and feel the product."},
  {de:"Das stimmt auch. Vielleicht ist eine Mischung am besten.",en:"That's true too. Maybe a mix is best."},
]},

// ═══════════════════════════════════════════════════════
//  ADVANCED CONVERSATIONS - C1 LEVEL
// ═══════════════════════════════════════════════════════
{id:"adv-1",title:"Political Discussion",category:"Society",level:"C1",exchanges:[
  {de:"Was hältst du von den aktuellen Entwicklungen in der Politik?",en:"What do you think about current developments in politics?"},
  {de:"Es ist eine komplexe Lage. Ich bin weder optimistisch noch pessimistisch.",en:"It's a complex situation. I'm neither optimistic nor pessimistic."},
  {de:"Was meinst du mit komplex?",en:"What do you mean by complex?"},
  {de:"Einerseits gibt es echte Fortschritte. Andererseits werden wichtige Themen ignoriert.",en:"On one hand there's real progress. On the other hand, important issues are being ignored."},
  {de:"Welche Themen zum Beispiel?",en:"Which issues, for example?"},
  {de:"Die soziale Ungleichheit nimmt zu, und die Politik handelt zu langsam.",en:"Social inequality is increasing, and politics is acting too slowly."},
  {de:"Das ist ein berechtigter Einwand. Aber was wäre die Alternative?",en:"That's a valid objection. But what would the alternative be?"},
  {de:"Mutigere Reformen. Wir können es uns nicht leisten, inkrementell vorzugehen.",en:"Bolder reforms. We cannot afford to proceed incrementally."},
  {de:"Ich teile deine Sorge, sehe es aber etwas differenzierter.",en:"I share your concern, but see it somewhat more nuancedly."},
]},
{id:"adv-2",title:"Ethical Dilemma",category:"Philosophy",level:"C1",exchanges:[
  {de:"Wie würdest du mit einem ethischen Dilemma am Arbeitsplatz umgehen?",en:"How would you deal with an ethical dilemma at work?"},
  {de:"Das hängt von der Schwere der Situation ab.",en:"That depends on the severity of the situation."},
  {de:"Angenommen, du siehst, dass ein Kollege Betrug begeht.",en:"Suppose you see a colleague committing fraud."},
  {de:"Das wäre eindeutig. Ich würde es melden, selbst wenn es schwierig ist.",en:"That would be clear. I would report it, even if it's difficult."},
  {de:"Und wenn es dein bester Freund wäre?",en:"And if it were your best friend?"},
  {de:"Dann würde ich zuerst mit ihm sprechen und ihn auffordern, es selbst zu melden.",en:"Then I would first talk to him and ask him to report it himself."},
  {de:"Und wenn er ablehnt?",en:"And if he refuses?"},
  {de:"Dann hätte ich keine andere Wahl, als es zu tun. Loyalität hat Grenzen.",en:"Then I'd have no choice but to do it. Loyalty has limits."},
  {de:"Das ist eine mutige Haltung. Nicht jeder würde so denken.",en:"That's a courageous stance. Not everyone would think like that."},
]},
{id:"adv-3",title:"Debating Globalisation",category:"Society",level:"C1",exchanges:[
  {de:"Siehst du die Globalisierung als Chance oder als Bedrohung?",en:"Do you see globalisation as an opportunity or a threat?"},
  {de:"Beides, würde ich sagen. Sie hat Wohlstand geschaffen, aber auch Probleme.",en:"Both, I would say. It has created prosperity but also problems."},
  {de:"Welche Probleme meinst du?",en:"What problems do you mean?"},
  {de:"Die zunehmende Abhängigkeit von globalen Lieferketten zum Beispiel.",en:"The increasing dependence on global supply chains, for example."},
  {de:"Das hat Corona deutlich gezeigt.",en:"Covid made that very clear."},
  {de:"Genau. Und die kulturelle Homogenisierung beunruhigt mich auch.",en:"Exactly. And cultural homogenisation worries me too."},
  {de:"Aber globaler Austausch bereichert doch auch die Kulturen.",en:"But global exchange enriches cultures too."},
  {de:"Das stimmt. Es ist eine zweischneidige Sache.",en:"That's true. It's a double-edged thing."},
  {de:"Vielleicht brauchen wir eine klügere, gerechtere Form der Globalisierung.",en:"Perhaps we need a smarter, fairer form of globalisation."},
]},

];
